### ISSUE TITLE
PMML gives different predictions than Python/XGBoost

### ISSUE THREAD

**Issue by ShalvaBagaturia** [jpmml/sklearn2pmml#303] opened 2021-09-27 10:42 UTC
I've faced an issue while trying to move XGboost regressor to PMML.
No missing data, no sparse / dense problem.

The following code illustrates an issue:
```
from sklearn2pmml import PMMLPipeline
from sklearn2pmml import make_pmml_pipeline
import sklearn2pmml
import xgboost as xgb

print(f'xgboost verstion={xgb.__version__}')
print(f'sklearn2pmml verstion={sklearn2pmml.__version__}')
print(f'pandas verstion={pd.__version__}')

# declare model
temp_model = xgb.XGBRegressor(base_score=0.05, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1.0,
             eval_metric=['poisson-nloglik'], gamma=0.75, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.09, max_delta_step=0.699999988, max_depth=5,
             min_child_weight=8.0, missing=1, monotone_constraints='()',
             n_estimators=343, n_jobs=-1, num_parallel_tree=1,
             objective='count:poisson', random_state=0, reg_alpha=0,
             reg_lambda=0.255, scale_pos_weight=None, subsample=0.8,
             tree_method='approx', validate_parameters=1, verbosity=None)
# read data
X = pd.read_csv('x.csv')
y = pd.read_csv('y.csv')
y.name = 'target'

# make pipeline
pipe = make_pmml_pipeline(temp_model, active_fields = X.columns.tolist(), target_fields = y.name)

pipe.fit(X, y)
pipe.configure(compact = False)

# Store pmml
sklearn2pmml.sklearn2pmml(pipe, pmml="./PMML/model.pmml", with_repr=True,debug=False)

from pypmml import Model
# Read pmml
model_pmml = Model.fromFile("./PMML/model.pmml")
predict_from_python = pd.DataFrame(pipe.predict(X), columns=['predict_python'])
predict_from_pmml = model_pmml.predict(X)
predict_from_pmml.columns=['predict_PMML']

# Compare predictions
concatenated = pd.concat([predict_from_python,predict_from_pmml], axis = 1)
concatenated['diff, %'] = (concatenated['predict_python'] - concatenated['predict_PMML'])/concatenated['predict_python']*100
concatenated
```
Here is the data
[y.csv](https://github.com/jpmml/sklearn2pmml/files/7235579/y.csv)

[x.csv](https://github.com/jpmml/sklearn2pmml/files/7235578/x.csv)

Any advice on this?

	predict_python	predict_PMML	diff, %
0	0.002885	0.002885	-0.000497
1	0.003630	0.003303	8.993513
**2	0.003787	0.002479	34.524170
3	0.017247	0.011201	35.054444**
4	0.003747	0.003747	-0.000359
...	...	...	...
995	0.003164	0.003994	-26.224410
996	0.002814	0.002981	-5.903927
997	0.008512	0.010744	-26.224429
998	0.017548	0.017692	-0.816182
999	0.001485	0.001806	-21.606424

**Comment by vruusmann** [comment] 2021-09-27 17:52
Closing as a likely duplicate of https://github.com/jpmml/jpmml-sklearn/issues/166

Please keep your findings in one place!

**Closed by vruusmann** 2021-09-27 17:52 UTC
