### ISSUE TITLE
Problem writing out categorical variable to JPMML file

### ISSUE THREAD

**Issue by puifais** [jpmml/sklearn2pmml#144] opened 2019-03-18 15:43 UTC
Hello,

I am having trouble writing out JPMML file with categorical variables. When I remove the categorical variables, I can write my numerical variables just fine. 

Here is my error trace:

```
Standard output is empty
Standard error:
Mar 18, 2019 3:35:46 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Mar 18, 2019 3:35:54 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 7610 ms.
Mar 18, 2019 3:35:54 PM org.jpmml.sklearn.Main run
INFO: Converting..
Mar 18, 2019 3:35:54 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException
	at org.jpmml.converter.ValueUtil.getDataType(ValueUtil.java:212)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at sklearn.TypeUtil.getDataType(TypeUtil.java:38)
	at sklearn2pmml.preprocessing.LookupTransformer.encodeFeatures(LookupTransformer.java:105)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:75)
	at sklearn.Initializer.encodeFeatures(Initializer.java:41)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:81)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:198)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

Exception in thread "main" java.lang.IllegalArgumentException
	at org.jpmml.converter.ValueUtil.getDataType(ValueUtil.java:212)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at sklearn.TypeUtil.getDataType(TypeUtil.java:38)
	at sklearn2pmml.preprocessing.LookupTransformer.encodeFeatures(LookupTransformer.java:105)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:75)
	at sklearn.Initializer.encodeFeatures(Initializer.java:41)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:81)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:198)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

Preserved joblib dump file(s): /tmp/pipeline-9o79z2_d.pkl.z

--------------------------------------------------------------------------
RuntimeError                             Traceback (most recent call last)
<ipython-input-25-91db46e5268e> in <module>
      5 filename = 'my_model.pmml'
      6 
----> 7 sklearn2pmml(pipeline_rf1, pathname+filename, debug=True)

~/usr1/local/lib/anaconda3/envs/puifai_env/lib/python3.6/site-packages/sklearn2pmml/__init__.py in sklearn2pmml(pipeline, pmml, user_classpath, with_repr, debug, java_encoding)
    250                                 print("Standard error is empty")
    251                 if retcode:
--> 252                         raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
    253         finally:
    254                 if debug:

RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
```

Here are versions of my packages:
```
python: 3.6.8
sklearn: 0.20.3
sklearn.externals.joblib: 0.13.0
pandas: 0.24.2
sklearn_pandas: 1.8.0
sklearn2pmml: 0.43.0
openjdk: 1.8.0_181
```
Would you please help me? :( I've tried several different combinations of versions of packages and nothing seems to work with my categorical.

**Comment by vruusmann** [comment] 2019-03-18 20:49
This issue is a functional duplicate of https://github.com/jpmml/sklearn2pmml/issues/70

In brief, the problem is that your `LookupTransformer` output column contains mixed data type values, and the converter is unable to "infer" what the intended data type should be.

To solve the problem, simply cast all output values to the same data type. Perhaps you have a mix of `int` and `string` values, or a mix of `integer` and `float` values there.

Specifically, see these two comments:
https://github.com/jpmml/sklearn2pmml/issues/70#issuecomment-352131617
https://github.com/jpmml/sklearn2pmml/issues/70#issuecomment-352134673

**Comment by vruusmann** [comment] 2019-03-18 21:06
> You may want to consider making the code automatically convert numpy.float to float.

I'm not a Python power user, so I wasn't aware of `numpy.float` vs `float` distinction.

Will have to investigate how the underlying Pyrolite library maps them to Java types. I suspect that `numpy.float` becomes some `ClassDict` object, whereas `float` becomes a regular `java.lang.Float` object.

Reopening to keep this on my radar.

**Comment by xiaowei1234** [comment] 2019-03-20 18:01
yea, this was the issue for my problem too. #145

I suspect a lot of people encounter this problem when they are trying to create a pmml file

**Closed** 2019-07-22 19:46 UTC
