### ISSUE TITLE
How to pass constant values to the PMML from PMMLPipeline in a custom transformer as an argument

### ISSUE THREAD

**Issue by chandimsett** [jpmml/sklearn2pmml#46] opened 2017-07-25 10:00 UTC
I am writing an exponential function x^n as a custom transformer. Where n is an argument which needs 
to be passed from the python pipeline to generate a PMML. I am able to create a PMML manually with the constant integer.
```
<DerivedField name="com.project.ai.jpmml.function.Exponent(number)" optype="continuous" dataType="double">
			<Apply function="com.project.ai.jpmml.function.Exponent">
				<FieldRef field="number"/>
				<Constant dataType="integer">3</Constant>
			</Apply>		
</DerivedField>
```

"number" is the name of the column where we want to apply the transformation with (number)^3. The transformation is applied in the JPMML custom transformer function 
successfully.
 But I need to pass 3 as an argument from the python PMML pipeline to generate the PMML with the above mentioned tag.
I am not able to pass that argument in the pipeline, however I was able to create custom transformer from the pipeline by passing the argument in the python 
custom transformer.
```
exponent=3
mapper = DataFrameMapper([(['number'],[customtransform_add(function="Exponent",arguments=exponent)]),('amount',None)])
pipeline = PMMLPipeline(
    [( "mapper", mapper) ,("classifier",clf)]     
)
```
Please help me with a solution, on how to send the argument to the PMML side so that it generates a <Constant> tag from the python pipeline.

**Comment by vruusmann** [comment] 2017-07-25 11:41
Duplicate of https://github.com/jpmml/jpmml-sklearn/issues/44

Will add a sample transformer class `com.mycompany.PowerFunction` into the [SkLearn2PMML-Plugin](https://github.com/jpmml/sklearn2pmml-plugin) project later today (or tomorrow).

There is no need to create a special-purpose Java-backed UDF for this. PMML provides a built-in function `pow` for raising numbers to arbitrary powers:
```xml
<Apply function="pow">
  <FieldRef field="number"/>
  <Constant dataType="integer">3</Constant>
</Apply>
```

**Closed by vruusmann** 2017-07-25 11:41 UTC

**Comment by chandimsett** [comment] 2017-07-25 12:10
Thanks for adding the function. For my use case, I  need to know how to pass the argument to a custom transformer function.  from the PMMLPipeline mapper. To be more specific, how do I create a Data Frame mapper which enables me to pass an argument for the respective custom transformer function, so that it creates a <Constant> markup carrying my argument in the PMML file for my custom transformer.
