### ISSUE TITLE
Support for  mutlioutput ? like   MLPRegressor    3 in  & 2 out

### ISSUE THREAD

**Issue by Nathanielll** [jpmml/sklearn2pmml#239] opened 2020-07-22 11:21 UTC
from sklearn2pmml import PMMLPipeline
from sklearn2pmml import sklearn2pmml
import pandas as pd
from sklearn.neural_network import MLPRegressor
import numpy as np

if __name__ == '__main__':
    X = pd.DataFrame(np.random.random((100, 3)), columns=['x1', 'x2', 'x3'])
    Y = pd.DataFrame(np.random.random((100, 2)), columns=['y1', 'y2'])
    clf = MLPRegressor()
    pipeline = PMMLPipeline([("classifier", clf)])
    clf.fit(X, Y)
    print(pipeline.predict([[1, 2, 3]]))
    sklearn2pmml(pipeline, "MLP{}.pmml".format(0), with_repr=True)

**And I got:**

Standard output is empty
Standard error:
 22, 2020 7:17:03  org.jpmml.sklearn.Main run
Ϣ: Parsing PKL..
 22, 2020 7:17:03  org.jpmml.sklearn.Main run
Ϣ: Parsed PKL in 49 ms.
 22, 2020 7:17:03  org.jpmml.sklearn.Main run
Ϣ: Converting..
 22, 2020 7:17:03  sklearn2pmml.pipeline.PMMLPipeline initTargetFields
: Attribute 'sklearn2pmml.pipeline.PMMLPipeline.target_fields' is not set. Assuming y as the name of the target field
 22, 2020 7:17:03  sklearn2pmml.pipeline.PMMLPipeline initActiveFields
: Attribute 'sklearn2pmml.pipeline.PMMLPipeline.active_fields' is not set. Assuming [x1, x2, x3] as the names of active fields
 22, 2020 7:17:03  org.jpmml.sklearn.Main run
: Failed to convert
java.lang.IllegalArgumentException
	at org.jpmml.converter.neural_network.NeuralNetworkUtil.createRegressionNeuralOutputs(NeuralNetworkUtil.java:160)
	at sklearn.neural_network.MultilayerPerceptronUtil.encodeNeuralNetwork(MultilayerPerceptronUtil.java:143)
	at sklearn.neural_network.MLPRegressor.encodeModel(MLPRegressor.java:49)
	at sklearn.neural_network.MLPRegressor.encodeModel(MLPRegressor.java:29)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:231)
	at org.jpmml.sklearn.Main.run(Main.java:233)
	at org.jpmml.sklearn.Main.main(Main.java:151)

Exception in thread "main" java.lang.IllegalArgumentException
	at org.jpmml.converter.neural_network.NeuralNetworkUtil.createRegressionNeuralOutputs(NeuralNetworkUtil.java:160)
	at sklearn.neural_network.MultilayerPerceptronUtil.encodeNeuralNetwork(MultilayerPerceptronUtil.java:143)
	at sklearn.neural_network.MLPRegressor.encodeModel(MLPRegressor.java:49)
	at sklearn.neural_network.MLPRegressor.encodeModel(MLPRegressor.java:29)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:231)
	at org.jpmml.sklearn.Main.run(Main.java:233)
	at org.jpmml.sklearn.Main.main(Main.java:151)

Traceback (most recent call last):
  File "G:/decisionTree.py", line 23, in <module>
    sklearn2pmml(pipeline, "MLP{}.pmml".format(0), with_repr=True)
  File "D:\Anaconda3\lib\site-packages\sklearn2pmml\__init__.py", line 266, in sklearn2pmml
    raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams

**Comment by vruusmann** [comment] 2020-07-22 18:54
Closing as duplicate of https://github.com/jpmml/jpmml-sklearn/issues/91

**Closed by vruusmann** 2020-07-22 18:54 UTC
