### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 2: invalid continuation byte 

### ISSUE THREAD

**Issue by jeff900911** [jpmml/sklearn2pmml#126] opened 2019-01-15 01:56 UTC
i checked the sklearn2pmml/_init.py_, it is the same with the "Added 'java_encoding' parameter. Fixes #120, fixes #122" styple,  but it is still has the problem. here is my code  

# -*- coding: utf-8 -*-
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor
from scipy.stats import ks_2samp
from sklearn import preprocessing
from sklearn import metrics
from xgboost.sklearn import XGBRegressor
from sklearn import utils
from numpy import nan as NA
from sklearn.externals import joblib
from sklearn2pmml import PMMLPipeline,sklearn2pmml
from sklearn_pandas import DataFrameMapper
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc

def good_bad_split(x, y, good_label=0, bad_label=1, good_size=0.6, bad_size=0.6):
    y_m = pd.DataFrame(y)
    y_m.columns = ['real_value']
    data = x.join(y_m)
    x_feature = list(data.columns)
    x_feature.remove('real_value')

    good_set = data[data['real_value'] == good_label]
    y_good = good_set['real_value']
    x_good = good_set[x_feature]
    x_good_train, x_good_test, y_good_train, y_good_test = train_test_split(x_good, y_good, test_size=good_size)

    bad_set = data[data['real_value'] == bad_label]
    y_bad = bad_set['real_value']
    x_bad = bad_set[x_feature]
    x_bad_train, x_bad_test, y_bad_train, y_bad_test = train_test_split(x_bad, y_bad, test_size=bad_size)

    x_train = pd.concat([x_good_test, x_bad_test])
    x_test = pd.concat([x_good_train, x_bad_train])
    y_train = pd.concat([y_good_test, y_bad_test])
    y_test = pd.concat([y_good_train, y_bad_train])
    good_len = len(x_good_test)
    bad_len = len(x_bad_test)
    return x_train, x_test, y_train, y_test, good_len, bad_len

if __name__ == '__main__':
    data = pd.read_csv('D:\\xgboost\\ivceshi.csv',encoding = 'ANSI')
    x_feature = [i for i in data.columns if i not in['Creditability']] # 移除无关数据
    data = data.dropna(axis=0, how='any')
    print(data.columns)
    print(x_feature)
    x = data[x_feature]
    y = data['Creditability']

    x_train, x_test, y_train, y_test, good_len, bad_len = good_bad_split(x, y)

    print(good_len, bad_len)

    pmml_pipeline = PMMLPipeline([
        ('regressor',XGBRegressor(learning_rate=0.1, n_estimators=30, max_depth=4, min_child_weight=4, gamma=0.1,
                       subsample=0.9, colsample_bytree=0.8, objective='binary:logistic', reg_alpha=1,
                       scale_pos_weight=1, seed=27))
    ])
    param_test = [{
        'regressor__max_depth': [i for i in range(1, 3)],
        'regressor__gamma': [i / 10.0 for i in range(0, 10)],
        'regressor__n_estimators': [i for i in range(2, 14, 2)],
    }]

    tuner = GridSearchCV(pmml_pipeline, param_grid=param_test, scoring='neg_mean_squared_error', n_jobs=4, iid=False, cv=5)
    tuner.fit(x_train,y_train)
    sklearn2pmml(tuner.best_estimator_,'xgbregressor_pipeline.pmml', with_repr=True)

**Comment by WilliamCHW** [comment] 2019-01-15 12:20
I use the isolation forest algorithm. If i choose the parameter of behaviour of  algorithm to equal to new,i have same problem with you, but if i choose  'behaviour '=old ,this problem will disappear.So i think sklearn2pmml package will  not be compatible with others packages.

**Comment by vruusmann** [comment] 2019-01-15 19:37
Closing as duplicate of #124 

The problem is not about the character encoding of CSV files, but the "default platform character encoding" of your computer as seen by `java.exe`. This problem only affects Chinese users, because your default platform character encoding is not UTF-8.

I do not have access to a Chinese-speaking computer, so I really can't reproduce and investigate this issue over here.

What you could do:
1. Save the PMMLPipeline instance into Python pickle file.
2. Convert this Pickle file using the JPMML-SkLearn command-line application; you can get the latest release version from here: https://github.com/jpmml/jpmml-sklearn/releases
3. Capture the output of JPMML-SkLearn command-line application to a log file:
```
java -jar jpmml-sklearn-executable-1.5.9.jar --pkl-input pipeline.pkl --pmml-output pipeline.pmml > log.txt 2>&1
```

This `log.txt` now contains all the bytes that were emitted by `java.exe` standard output and error streams. Attach this log file to issue #124 so that I could analyze it.

**Closed by vruusmann** 2019-01-15 19:37 UTC

**Comment by vruusmann** [comment] 2019-01-15 19:39
@jeff900911 Please note that if you're using a Chinese-speaking computer, then you need to specify the `java_encoding` attribute. It defaults to UTF-8, which is the root cause of the problem.
