### ISSUE TITLE
LabelBinarizer vs PMMLLabelBinarizer for two class

### ISSUE THREAD

**Issue by xiaowei1234** [jpmml/sklearn2pmml#137] opened 2019-03-05 17:38 UTC
Hey Villu,

Not sure if it's intentional or not on your part but PMMLLabelBinarizer does not equal sklearn.preprocessing.LabelBinarizer when used on column with two classes.

```
lb = PMMLLabelBinarizer()
lb.fit_transform([False, True])
array([[1, 0],
       [0, 1]])

lb = LabelBinarizer()
lb.fit_transform([False, True])
array([[0],
       [1]])
```

**Comment by vruusmann** [comment] 2019-03-05 18:41
@xiaowei1234 Why do you ask - is there a problem with the generated PMML document?

All the one-hot-encoding and label binarization work is reduced to no-op in the PMML representation. So, in principle, it shouldn't matter if there is temporarily one column extra in your `X` matrix or not.

My `PMMLLabelBinarizer` and `PMMLLabelEncoder` classes are missing value-aware replacements for Scikit-Learn's `LabelBinarizer` and `LabelEncoder` classes, respectively. They are needed when you want to pass missing values (ie. `None`) through your pipeline so that the eventual estimator step could see them as-is. You don't need this functionality with most built-in Scikit-Learn estimator classes. But it might come handy when dealing with third party ML libraries such as XGBoost or LightGBM.

Example about `PMMLLabelBinarizer` vs `LabelBinarizer` difference:
```
from sklearn2pmml.preprocessing import PMMLLabelBinarizer
plb = PMMLLabelBinarizer()
plb.fit_transform([False, None, True, False])
array([[1, 0],
       [0, 0],
       [0, 1],
       [1, 0]])

from sklearn.preprocessing import LabelBinarizer
pl = LabelBinarizer()
pl.fit_transform([False, None, True, False])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.4/site-packages/sklearn/preprocessing/label.py", line 436, in fit_transform
    return self.fit(y).transform(y)
  File "/usr/lib64/python3.4/site-packages/sklearn/preprocessing/label.py", line 413, in fit
    self.classes_ = unique_labels(y)
  File "/usr/lib64/python3.4/site-packages/sklearn/utils/multiclass.py", line 96, in unique_labels
    raise ValueError("Unknown label type: %s" % repr(ys))
ValueError: Unknown label type: ([False, None, True, False],)
```

**Comment by vruusmann** [comment] 2019-03-05 18:45
Apparently, `PMMLabelBinarizer` encodes a missing value as an all-zeroes row. Only `PMMLLabelEncoder` is able to pass through missing values as-is:
```
from sklearn2pmml.preprocessing import PMMLLabelEncoder
ple = PMMLLabelEncoder()
ple.fit_transform([False, None, True, False])
array([0, None, 1, 0], dtype=object)
```

Everything seems to work as intended/advertised, so closing this issue.

**Closed by vruusmann** 2019-03-05 18:45 UTC
