### ISSUE TITLE
xgb 生成的pkl 转pmml 失败

### ISSUE THREAD

**Issue by songsong124** [jpmml/sklearn2pmml#405] opened 2024-01-15 08:10 UTC
python: 3.8.2
sklearn2pmml: 0.101.0
sklearn: 1.3.2
sklearn_pandas: 2.2.0
pandas: 2.0.3
numpy: 1.24.4
dill: 0.3.7
joblib: 1.3.2
java: 1.8.0_192

```
Executing command:
java -cp /usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/sklearn2pmml-1.0-SNAPSHOT.jar:/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/gson-2.10.1.jar:/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/guava-32.1.1-jre.jar:/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/h2o-genmodel-3.44.0.3.jar:/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/h2o-logger-3.44.0.3.jar:/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/h2o-tree-api-0.3.17.jar:/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/istack-commons-runtime-4.0.1.jar:/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/jackson-annotations-2.13.3.jar:/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/jakarta.activation-2.0.1.jar:/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/jakarta.xml.bind-api-3.0.1.jar:/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/jaxb-core-3.0.2.jar:/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/jaxb-runtime-3.0.2.jar:/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/jcommander-1.72.jar:/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/pickle-1.5.jar:/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/pmml-converter-1.5.5.jar:/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/pmml-h2o-1.2.10.jar:/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/pmml-lightgbm-1.5.0.jar:/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/pmml-model-1.6.4.jar:/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/pmml-model-metro-1.6.4.jar:/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/pmml-python-1.1.19.jar:/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/pmml-sklearn-1.7.46.jar:/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/pmml-sklearn-extension-1.7.46.jar:/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/pmml-sklearn-h2o-1.7.46.jar:/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/pmml-sklearn-lightgbm-1.7.46.jar:/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/pmml-sklearn-statsmodels-1.7.46.jar:/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/pmml-sklearn-xgboost-1.7.46.jar:/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/pmml-statsmodels-1.0.6.jar:/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/pmml-xgboost-1.8.1.jar:/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/serpent-1.40.jar:/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/slf4j-api-1.7.36.jar:/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/slf4j-jdk14-1.7.36.jar:/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/ubjson-0.1.8.jar:/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/resources/ubjson-gson-0.1.8.jar com.sklearn2pmml.Main --pkl-input /tmp/estimator-41ac0puk.pkl.z --pmml-output /root/PycharmProjects/phishing-website-detection/output/phishing_detection_model111.pmml
Traceback (most recent call last):
  File "/root/PycharmProjects/phishing-website-detection/pkltopmml.py", line 7, in <module>
    sklearn2pmml(pipeline, '/root/PycharmProjects/phishing-website-detection/output/phishing_detection_model111.pmml', with_repr=True, debug=True)
  File "/usr/local/python3/lib/python3.8/site-packages/sklearn2pmml/__init__.py", line 325, in sklearn2pmml
    raise RuntimeError("The SkLearn2PMML application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
RuntimeError: The SkLearn2PMML application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
Standard output is empty
Standard error:
?? 15, 2024 3:53:02 ?? sklearn2pmml.pipeline.PMMLPipeline initTargetFields
??: Attribute 'sklearn2pmml.pipeline.PMMLPipeline.target_fields' is not set. Assuming [y] as the name(s) of the target field(s)
Exception in thread "main" java.lang.IllegalArgumentException: The classifier object does not have a persistent 'classes_' attribute. Please set the 'xgboost.sklearn.XGBClassifier.pmml_classes_' attribute
	at xgboost.sklearn.XGBClassifier.getClasses(XGBClassifier.java:62)
	at sklearn.CompositeClassifier.getClasses(CompositeClassifier.java:92)
	at sklearn.Classifier.encodeLabel(Classifier.java:108)
	at org.jpmml.sklearn.SkLearnEncoder.initLabel(SkLearnEncoder.java:147)
	at sklearn.Composite.initLabel(Composite.java:225)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:103)
	at com.sklearn2pmml.Main.run(Main.java:80)
	at com.sklearn2pmml.Main.main(Main.java:65)
Caused by: java.lang.IllegalArgumentException: Attribute 'xgboost.sklearn.XGBClassifier.classes_' not set
	at org.jpmml.python.PythonObject.get(PythonObject.java:82)
	at org.jpmml.python.PythonObject.getList(PythonObject.java:282)
	at org.jpmml.python.PythonObject.getListLike(PythonObject.java:311)
	at sklearn.Classifier.getClasses(Classifier.java:91)
	at sklearn.LabelEncoderClassifier.getClasses(LabelEncoderClassifier.java:40)
	at xgboost.sklearn.XGBClassifier.getClasses(XGBClassifier.java:57)
	... 7 more

Preserved dump file(s): /tmp/estimator-41ac0puk.pkl.z
```

**Comment by vruusmann** [comment] 2024-01-15 08:26
> Caused by: java.lang.IllegalArgumentException: Attribute 'xgboost.sklearn.XGBClassifier.classes_' not set

This issue is an exact duplicate of https://github.com/jpmml/sklearn2pmml/issues/402

For reasons unknown to me, XGBoost developers decided to remove the `XGBClassifier.classes_` attribute in XGBoost 2.0.X. However, this attribute is needed for the definition of the target field, so it needs to be re-set manually after the pipeline has been fitted.

See here: https://github.com/jpmml/sklearn2pmml/issues/402#issuecomment-1860916960

**Closed by vruusmann** 2024-01-15 08:26 UTC
