### ISSUE TITLE
encounter exceptions when export PCA model

### ISSUE THREAD

**Issue by wunderbarr** [jpmml/sklearn2pmml#153] opened 2019-05-14 10:08 UTC
Hello,
I would like to export PCA model. The shape of my dataframe is 2232*25, so it would be hard to specify column names. 
```
pipeline = PMMLPipeline([("pca", PCA(n_components = 2))])
pipeline.fit_transform(df)
sklearn2pmml(pipeline, "./models/pca.pmml")
```
And I obtain:
```
Standard output is empty
Standard error:
May 14, 2019 5:04:14 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
May 14, 2019 5:04:14 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 15 ms.
May 14, 2019 5:04:14 PM org.jpmml.sklearn.Main run
INFO: Converting..
May 14, 2019 5:04:14 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException: Expected an estimator object as the last step, got a transformer object (Python class sklearn.decomposition.pca.PCA)
        at sklearn2pmml.pipeline.PMMLPipeline.getEstimator(PMMLPipeline.java:541)
        at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:93)
        at org.jpmml.sklearn.Main.run(Main.java:145)
        at org.jpmml.sklearn.Main.main(Main.java:94)

Exception in thread "main" java.lang.IllegalArgumentException: Expected an estimator object as the last step, got a transformer object (Python class sklearn.decomposition.pca.PCA)
        at sklearn2pmml.pipeline.PMMLPipeline.getEstimator(PMMLPipeline.java:541)
        at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:93)
        at org.jpmml.sklearn.Main.run(Main.java:145)
        at org.jpmml.sklearn.Main.main(Main.java:94)

Traceback (most recent call last):
  File ".../models/pca.py", line 12, in <module>
    sklearn2pmml(pipeline, "./models/pca.pmml")
  File ".../.local/lib/python3.5/site-packages/sklearn2pmml/__init__.py", line 252, in sklearn2pmml
    raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
```
Is it possible to only export PCA PMML files?
Thank you!

**Comment by vruusmann** [comment] 2019-05-14 10:38
> Is it possible to only export PCA PMML files?

The exception message that you're reporting is supposed to communicate that this is currently not possible.

Closing this issue as a functional duplicate of https://github.com/jpmml/jpmml-sklearn/issues/86

**Closed by vruusmann** 2019-05-14 10:38 UTC
