### ISSUE TITLE
Create .pmml File for Calibrated xgboost Model

### ISSUE THREAD

**Issue by mlsquareup** [jpmml/sklearn2pmml#415] opened 2024-03-09 05:11 UTC
Hi, I'm wondering if it's possible to convert an xgboost -> isotonic regression model into a .pmml artifact. Here's roughly what I'm trying to do:

```python
# not actually runnable
import xgboost
classifier = xgboost.XGBClassifier(
    ... 
)

from sklego.meta import EstimatorTransformer
xgb_transformer = EstimatorTransformer(classifier, predict_func = 'predict_proba')

with open('calibration_artifact.pickle', 'rb') as f:
    ir = pickle.load(f) # Some fitted IsotonicRegression from sklearn.isotonic
ir

from sklearn2pmml import PMMLPipeline
from sklearn2pmml.preprocessing import ExpressionTransformer
pipeline = PMMLPipeline(
    steps = (
        [
           ("classifier", xgb_transformer),
            ("probability_extractor", ExpressionTransformer("X[1]")),
            ("calibrator", ir),
        ]
    )
)

from sklearn2pmml import sklearn2pmml
sklearn2pmml(pipeline, "model_pipeline.pmml", with_repr = False, debug=True)
```

Here's the error I'm seeing from it:

```
Standard output is empty
Standard error:
Exception in thread "main" java.lang.IllegalArgumentException: Attribute 'sklearn2pmml.pipeline.PMMLPipeline.steps' has an unsupported value (Java class [Ljava.lang.Object;)
	at org.jpmml.python.CastFunction.apply(CastFunction.java:47)
	at org.jpmml.python.PythonObject.get(PythonObject.java:108)
	at org.jpmml.python.PythonObject.getList(PythonObject.java:282)
	at org.jpmml.python.PythonObject.getList(PythonObject.java:286)
	at org.jpmml.python.PythonObject.getTupleList(PythonObject.java:300)
	at sklearn.pipeline.SkLearnPipeline.getSteps(SkLearnPipeline.java:221)
	at sklearn2pmml.pipeline.PMMLPipeline.getSteps(PMMLPipeline.java:418)
	at sklearn.pipeline.SkLearnPipeline.hasFinalEstimator(SkLearnPipeline.java:70)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:100)
	at com.sklearn2pmml.Main.run(Main.java:80)
	at com.sklearn2pmml.Main.main(Main.java:65)
Caused by: java.lang.ClassCastException: Cannot cast [Ljava.lang.Object; to java.util.List
	at java.base/java.lang.Class.cast(Class.java:3605)
	at org.jpmml.python.CastFunction.apply(CastFunction.java:45)
	... 10 more

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-318-185d7e9e2b50> in <module>
      1 from sklearn2pmml import sklearn2pmml
----> 2 sklearn2pmml(pipeline, "xgb_with_isotonic_calibration.pmml")

/usr/local/lib/python3.7/dist-packages/sklearn2pmml/__init__.py in sklearn2pmml(estimator, pmml_path, with_repr, java_home, java_opts, user_classpath, dump_flavour, debug)
    323                                 print("Standard error is empty")
    324                 if retcode:
--> 325                         raise RuntimeError("The SkLearn2PMML application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
    326         finally:
    327                 if debug:

RuntimeError: The SkLearn2PMML application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
```

For further context we need the .pmml artifact output because an internal service consumes it for model hosting.

**Comment by vruusmann** [comment] 2024-03-09 06:21
> Caused by: java.lang.ClassCastException: Cannot cast [Ljava.lang.Object; to java.util.List
>	at java.base/java.lang.Class.cast(Class.java:3605)

This particular exception is caused by bad `(PMML)Pipeline` initialization syntax.

Right now, you have `steps = ([])` (ie. a list inside a single-element tuple), but you should be having `steps = [..]` (ie. a standalone list).

**Comment by vruusmann** [comment] 2024-03-09 06:31
Anyway, to cheer you up, then the intended workflow - "calibrating XGBoost probabilities using a (pre-fitted-) isitonic regression" is totally doable in PMML.

There are two options:
1. The built-in `CalibratedClassifierCV` approach. Essentially, you'd need to build a new CCCV instance using your pre-fitted components.
2. The custom "prediction post-processing" approach. The `PMMLPipeline` has an `predict_proba_transformer` attribute, which accepts a list of transformers and transformer-like estimators (such as `IsotinicRegression`) that will be applied to the "raw" `XGBClassifier.predict_proba(X)` values, resulting in "post-processed" values.

The second option would be implemented like this:
```python
calibrator = joblib.load("calibrator.pkl")

pipeline = PMMLPipeline([
  ("classifier", XGBClassifier(...))
], predict_proba_transformer = [ExpressionTransformer("X[1]"), EstimatorTransformer(calibrator)])
```

**Comment by vruusmann** [comment] 2024-03-09 06:49
It it a common use case, where a new estimator instance (eg. `XGBClassifier(...)`) and a an existing estimator (eg. `IsotonicRegression`) need to be combined into a single pipeline?

```python
steps = [
   ("classifier", XGBClassifier(...)),
    ("calibrator", ir),
]
```

Right now, the pipeline cannot be fitted (because that would destroy the existing `ir` object state), and it also cannot be used for prediction (because the `XGBClassifier(...)` object is in uninitalized state).

This pipeline could be made fittable, if the `ir` object was wrapped into some no-op "state protecting" meta-estimator:

``` python
steps = [
   ("classifier", XGBClassifier(...)),
    ("calibrator", IgnoreFitEstimator(ir)),
]

pipeline = Pipeline(steps)
pipeline.fit(X, y)
```

If the pipeline is fittable, then all sorts of Python syntax errors and stuff would become immediately visible.

**Comment by mlsquareup** [comment] 2024-03-19 16:32
Thanks for the prompt response @vruusmann ! I always appreciate your insight and expertise on PMML matters. So I've tried the second approach using the following:

```
pipeline = PMMLPipeline([
  ("classifier", pretrained_xgboost_model)
], predict_proba_transformer = [ExpressionTransformer("X[1]"), EstimatorTransformer(ir)])
```

where the model/isotonic regression is already trained. I can verify that pipeline.predict works and produces outputs. Then when I run

```
from sklearn2pmml import sklearn2pmml
sklearn2pmml(pipeline, "model_pipeline.pmml", with_repr = False, java_opts=["-Xms4096m", "-Xmx4096m"], debug=True)
```
I see the following error:
```

python: 3.9.18
sklearn2pmml: 0.104.1
sklearn: 1.4.1.post1
pandas: 1.5.3
numpy: 1.26.4
dill: 0.3.8
joblib: 1.3.2
openjdk: 11.0.22
Executing command:
java -Xms4096m -Xmx4096m -cp /code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/sklearn2pmml-1.0-SNAPSHOT.jar:/code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/gson-2.10.1.jar:/code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/guava-33.0.0-jre.jar:/code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/h2o-genmodel-3.44.0.3.jar:/code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/h2o-logger-3.44.0.3.jar:/code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/h2o-tree-api-0.3.17.jar:/code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/istack-commons-runtime-4.0.1.jar:/code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/jackson-annotations-2.13.3.jar:/code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/jakarta.activation-2.0.1.jar:/code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/jakarta.xml.bind-api-3.0.1.jar:/code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/jaxb-core-3.0.2.jar:/code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/jaxb-runtime-3.0.2.jar:/code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/jcommander-1.72.jar:/code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/pickle-1.5.jar:/code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/pmml-converter-1.5.6.jar:/code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/pmml-h2o-1.2.11.jar:/code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/pmml-lightgbm-1.5.2.jar:/code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/pmml-model-1.6.4.jar:/code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/pmml-model-metro-1.6.4.jar:/code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/pmml-python-1.1.21.jar:/code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/pmml-sklearn-1.7.53.jar:/code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/pmml-sklearn-extension-1.7.53.jar:/code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/pmml-sklearn-h2o-1.7.53.jar:/code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/pmml-sklearn-lightgbm-1.7.53.jar:/code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/pmml-sklearn-statsmodels-1.7.53.jar:/code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/pmml-sklearn-xgboost-1.7.53.jar:/code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/pmml-statsmodels-1.0.7.jar:/code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/pmml-xgboost-1.8.3.jar:/code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/serpent-1.40.jar:/code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/slf4j-api-1.7.36.jar:/code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/slf4j-jdk14-1.7.36.jar:/code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/ubjson-0.1.8.jar:/code/.venv/lib/python3.9/site-packages/sklearn2pmml/resources/ubjson-gson-0.1.8.jar com.sklearn2pmml.Main --pkl-input /tmp/estimator-lq1ybyn_.pkl.z --pmml-output model_pipeline.pmml
Standard output is empty
Standard error:
Exception in thread "main" java.lang.IllegalArgumentException: Attribute 'sklearn2pmml.pipeline.PMMLPipeline.predict_proba_transformer' has an unsupported value (Java class java.util.ArrayList)
	at org.jpmml.python.CastFunction.apply(CastFunction.java:47)
	at org.jpmml.python.PythonObject.get(PythonObject.java:108)
	at org.jpmml.python.PythonObject.getOptional(PythonObject.java:118)
	at sklearn2pmml.pipeline.PMMLPipeline.getTransformer(PMMLPipeline.java:491)
	at sklearn2pmml.pipeline.PMMLPipeline.getPredictProbaTransformer(PMMLPipeline.java:483)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:96)
	at com.sklearn2pmml.Main.run(Main.java:80)
	at com.sklearn2pmml.Main.main(Main.java:65)
Caused by: java.lang.ClassCastException: Cannot cast java.util.ArrayList to sklearn.Transformer
	at java.base/java.lang.Class.cast(Class.java:3605)
	at org.jpmml.python.CastFunction.apply(CastFunction.java:45)
	... 7 more

Preserved dump file(s): /tmp/estimator-lq1ybyn_.pkl.z
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_6312/1477334889.py in <cell line: 2>()
      1 from sklearn2pmml import sklearn2pmml
----> 2 sklearn2pmml(pipeline, "model_pipeline.pmml", with_repr = False, java_opts=["-Xms4096m", "-Xmx4096m"], debug=True)

/code/.venv/lib/python3.9/site-packages/sklearn2pmml/__init__.py in sklearn2pmml(estimator, pmml_path, with_repr, java_home, java_opts, user_classpath, dump_flavour, debug)
    328                                 print("Standard error is empty")
    329                 if retcode:
--> 330                         raise RuntimeError("The SkLearn2PMML application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
    331         finally:
    332                 if debug:

RuntimeError: The SkLearn2PMML application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
```

Am I implementing the second approach correctly?

**Comment by vruusmann** [comment] 2024-03-19 17:14
> Exception in thread "main" java.lang.IllegalArgumentException: Attribute 'sklearn2pmml.pipeline.PMMLPipeline.predict_proba_transformer' has an unsupported value (Java class java.util.ArrayList)

It's a syntactic error again - the value of the `PMMLPipeline.predict_proba_transformer` attribute should be a single transformer object.

Right now you have provided a list of transformers. The easiest way to satisfy the "single transformer" object requirement is to pack the list into a `Pipeline` object (see the API docs for the `sklearn.pipeline.make_pipeline` function yourself - I believe it expects transformer objects, without any list wrappers):

``` python
from sklearn.pipeline import make_pipeline

pipeline = PMMLPipeline([
  ...
], predict_proba_transformer = make_pipeline(ExpressionTransformer("X[1]"), EstimatorTransformer(ir)))
```

You can veryfy the setup by invoking the `PMMLPipeline.predict_proba_transform(X)` method. If the Python side yields a result (ie. doesn't error out with any syntactic errors), then the conversion to PMML should succeed as well.

Also, right now both transformer elements are stateless/pre-fitted like. If you need to use some stateful transformers there, then you need to pre-fit the pipeline object manually before assigning it to the `PMMLPipeline.predict_proba_transformer` attribute:

``` python
pipeline = PMMLPipeline([..])
pipeline.fit(X, y)

# Get the predicted probabilities matrix based on training data
y_proba = pipeline.predict_proba(X)

# Train a secondary pipeline, where y_proba is the input
predict_proba_transformer = make_pipeline(...)
predict_proba.fit(X = y_proba, y = None)

# Now put everything together
pipeline.predict_proba_transformer = predict_proba_transformer
```

**Comment by vruusmann** [comment] 2024-03-19 17:19
There is also a mechanism available for referencing `X` columns from within `PMMLPipeline.predict_transformer`, and `PMMLPipeline.predict_proba_transformer` (eg. thresholding against some user-provided values).

The mechanism is called "feature cross-references":
https://openscoring.io/blog/2023/11/25/sklearn_feature_cross_references/

Can provide an example if needed.

@mlsquareup What do you think, will be there a need for `PrefittedTransformer` and `PrefittedTransformer` (pseudo-)estimator classes? They wouldn't be difficult to implement, but would allow for some quite interesting workflows around pre-fitted components (eg. reusing a fixed calibration curve during training).

**Comment by vruusmann** [comment] 2024-04-02 16:13
Did some more research about calibrating classifiers (XGBoost or any other) using `IsotonicRegression`. It seems to me that the workflow can be assembled into a single `CalibratedClassifierCV` object; there is no need for a pipeline, or `EstimatorTransformer` objects at all.

First,  let's train a classifier that needs calibration:
``` python
from sklearn.datasets import load_iris
from xgboost.sklearn import XGBClassifier

X, y = load_iris(return_X_y = True)

# Change target from multiclass to binary
y = (y == 1).astype(int)

classifier = XGBClassifier(n_estimators = 7)
classifier.fit(X, y)

proba_raw = classifier.predict_proba(X)
print(proba_raw)
```

Second, let's wrap this pre-fitted into a `CalibratedClassifierCV` object. Its parameterized with the above pre-fitted classifier object, and the calibration method is requested to be `isotonic`:

``` python
from sklearn.calibration import CalibratedClassifierCV

calibrated_classifier = CalibratedClassifierCV(
	estimator = classifier,
	cv = "prefit",
	method = "isotonic",
)
calibrated_classifier.fit(X, y)

proba_calib = calibrated_classifier.predict_proba(X)
print(proba_calib)
```

This `CalibratedClassifierCV` object can be directly exported into the PMML representation using the SkLearn2PMML package. There is no need to wrap it into a `PMMLPipeline`:

``` python
from sklearn2pmml import sklearn2pmml

sklearn2pmml(calibrated_classifier, "CalibratedClassifier.pmml")
```

Now comes the fun part - replacing the existing "dummy" isotonic calibration function with a "production ready" one.

The calibrator object is located at `CalibratedClassifierCV.calibrated_classifiers_[<index A>].calibrators[<index B>]`. In the `cv = "prefit"` mode, these two lists are both singleton lists. So, we simply override the first calibrator element that we come across:

``` python
from sklearn.base import clone

# Get calibrator
calibrator = calibrated_classifier.calibrated_classifiers_[0].calibrators[0]
print(calibrator)

# Customize the calibration curve of the calibrator
custom_calibrator = clone(calibrator)
custom_calibrator.X_thresholds_ = numpy.asarray([0.05, 0.25, 0.55, 0.75, 0.95])
custom_calibrator.y_thresholds_ = numpy.asarray([0.1, 0.3, 0.6, 0.85, 0.99])

# Set custom calibrator
calibrated_classifier.calibrated_classifiers_[0].calibrators[0] = cust_calibrator

sklearn2pmml(calibrated_classifier, "CalibratedClassifier-custom.pmml")
```

When exporting `CalibratedClassifierCV` objects into the PMML representation, then the result has a nice and clean classifier-type model schema:

- The predicted label field (ie. `CalibratedClassifierCV.predict(X)` results)
- Two predicted probability fields (ie. `CalibratedClassifierCV.predict_proba(X)` results)

When needed, then it's possible to also extract and expose the intermediate "raw" probability fields (ie. `XGBClassifier.predict_proba(X)` results).

**Closed by vruusmann** 2024-04-02 16:13 UTC
