### ISSUE TITLE
Support for predict_proba method in SelectFirstEstimator

### ISSUE THREAD

**Issue by ddzhem** [jpmml/sklearn2pmml#199] opened 2019-12-18 07:17 UTC
Hi! According to source code, SelectFirstEstimator has only predict() method in it, but in many classification tasks it would be great to have option of predicting probability. Is it possible to implement predict_proba method in this Estimator, that would be just great!

**Comment by vruusmann** [comment] 2019-12-18 07:42
> According to source code, SelectFirstEstimator has only predict() method in it.

The distinction between `predict(X)` and `predict_proba(X)` only exists in the Scikit-Learn side.

In the (J)PMML side, probabilistic classifiers have exactly the same public API as non-probabilistic classifiers. So, if you construct a `SelectFirstEstimator` using probabilistic classifiers such as `LogisticRegression`, then you should receive a PMML file that predicts probabilities already today.

**Comment by ddzhem** [comment] 2019-12-18 07:53
So, my PMMLPipeline won't be able to predict probabilities in Python environment, but it'll be fine when converted to .pmml , right?

**Comment by vruusmann** [comment] 2019-12-18 08:24
> .. but it'll be fine when converted to .pmml?

Yes, the (J)PMML side is more functional that the Scikit-Learn side.

Here's my integration test with probabilistic classifiers:
https://github.com/jpmml/jpmml-sklearn/blob/master/src/test/resources/main.py#L456-L480

Since the `SelectFirstEstimator.fit(X, y)` method is disabled (raises `NotImplementedError`), then I'm constructing a `PMMLPipeline` instance manually.

**Comment by vruusmann** [comment] 2019-12-18 08:26
It's good that we have this issue open right now. I've been thinking about implementing `SelectFirstEstimator.fit(X, y)` for quite some time, and there's a good chance that it'll happen (together with `SelectFirstEstimator.predict_proba(X)`) already in the next SkLearn2PMML package version.

**Comment by ddzhem** [comment] 2019-12-18 08:30
That's great news! Thanks for such a quick answer!

**Comment by vruusmann** [comment] 2019-12-19 06:55
@ddzhem I've pushed a preview of the `SelectFirstEstimator.fit(X, y)` method to GitHub.

There's also an updated `predict(X)` method, which you can use as a template for your quick `predict_proba(X)` method prototype. The latter will be rather challenging to implement, because there are all sorts of pre- and post-conditions that needs to be checked in Python code. For example, making sure that all probability distributions have the same class composition and dimensionality.

**Closed** 2020-03-04 07:34 UTC
