### ISSUE TITLE
sklearn2pmml supoort user-defined tranformer ?

### ISSUE THREAD

**Issue by joyzhou28** [jpmml/sklearn2pmml#183] opened 2019-10-09 11:15 UTC
I've wrote some self-defined tranformer, pipeline runs ok but failed to export to pmml.

**Comment by vruusmann** [comment] 2019-10-09 19:07
Duplicate of https://github.com/jpmml/sklearn2pmml/issues/172, https://github.com/jpmml/sklearn2pmml/issues/108, and a few others

**Closed by vruusmann** 2019-10-09 19:07 UTC
