### ISSUE TITLE
Handling `LogisticRegression.multi_class=auto` attribute value

### ISSUE THREAD

**Issue by pranaviMVC13** [jpmml/sklearn2pmml#166] opened 2019-07-11 02:04 UTC
hi, 

Trying to convert my logistic regression model to pmml, and the conversion fails. It was working till yesterday and i could generate a pmml. I havent chnaged versions of my sklearn, or pandas or any other package after that. Today when i run it gives me the following error: 
```
Standard output is empty
Standard error:
Picked up JAVA_TOOL_OPTIONS: -Xmx1024m 
Jul 10, 2019 9:39:36 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Jul 10, 2019 9:39:36 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 22 ms.
Jul 10, 2019 9:39:36 PM org.jpmml.sklearn.Main run
INFO: Converting..
Jul 10, 2019 9:39:36 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException: auto
	at sklearn.linear_model.logistic.LogisticRegression.encodeModel(LogisticRegression.java:64)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:213)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

Exception in thread "main" java.lang.IllegalArgumentException: auto
	at sklearn.linear_model.logistic.LogisticRegression.encodeModel(LogisticRegression.java:64)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:213)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-40-2d1481ceed96> in <module>()
----> 1 sklearn2pmml(pipeline, "LogisticRegressionMNV.pmml", with_repr = True)

~/.local/lib/python3.6/site-packages/sklearn2pmml/__init__.py in sklearn2pmml(pipeline, pmml, user_classpath, with_repr, debug, java_encoding)
    250                                 print("Standard error is empty")
    251                 if retcode:
--> 252                         raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
    253         finally:
    254                 if debug:

RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
```
I cannot figure out the issue.

sklearn version : 0.20.0
python 3.6

Could you please help me figure out the issue.

**Comment by vruusmann** [comment] 2019-07-11 04:43
> SEVERE: Failed to convert
> java.lang.IllegalArgumentException: auto
> 	at sklearn.linear_model.logistic.LogisticRegression.encodeModel(LogisticRegression.java:64)
> 	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:213)

This exception points to line 64 of `sklearn.linear_model.logistic.LogisticRegression` Java source code file:
https://github.com/jpmml/jpmml-sklearn/blob/master/src/main/java/sklearn/linear_model/logistic/LogisticRegression.java#L64

It's easy to see that this complaint is about unsupported `multi_class` attribute value. It should be one of `ovr` or `multinomial`, but you've left it unspecified.

**Comment by vruusmann** [comment] 2019-07-11 04:45
The mapping of the `auto` attribute value is Scikit-Learn value specific.

So far, I haven't added this Scikit-Learn version detection logic there, but maybe I should. Taking my time to contemplate about it, and then will either fix or close this issue as "works as intended".

**Comment by pranaviMVC13** [comment] 2019-07-11 17:23
Thank you for your quick response, as of now specifying auto isn't working so i left it unspecified and it didn't throw any error. So i am assuming it defaults to 'ovr' if it is binary and 'multinomial' if it is muticlass.

**Comment by vruusmann** [comment] 2019-11-24 14:49
Closing as "won't fix", because I don't have time to track Scikit-Learn attribute defaults in the JPMML-SkLearn library code. Sooner or later I'd miss some update, and then then it would become even more difficult to troubleshoot.

I believe that newer Scikit-Learn versions already raise a notification/warning when an attribute value is left as `auto`. Pay attention to those first.

**Closed by vruusmann** 2019-11-24 14:49 UTC
