### ISSUE TITLE
Support for older version of pmml files

### ISSUE THREAD

**Issue by mcoplan11** [jpmml/sklearn2pmml#262] opened 2021-01-19 22:03 UTC
There should be an additional parameter to specify the version of pmml file used to export.

for example,

`sklearn2pmml(pipeline, "logmodel_readmission_2.pmml" , version=4.3)
`

**Comment by vruusmann** [comment] 2021-01-20 16:05
Closing as exact duplicate of https://github.com/jpmml/sklearn2pmml/issues/262

**Closed by vruusmann** 2021-01-20 16:05 UTC

**Comment by vruusmann** [comment] 2021-01-20 16:06
> There should be an additional parameter to specify the version of pmml file used to export.

Why would I want to create legacy PMML schema version documents?

Who is going tto pay for their development and maintenance?
