### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 1: invalid continuation byte

### ISSUE THREAD

**Issue by sylvainferrec** [jpmml/sklearn2pmml#122] opened 2018-12-07 13:22 UTC
Hi,

**I am trying to run the following code to export my tfidf-SVM pipeline into a PMML format:**

_from sklearn2pmml import PMMLPipeline
from sklearn2pmml.feature_extraction.text import Splitter
from sklearn2pmml import sklearn2pmml

Textpipeline = PMMLPipeline([
("tf-idf", TfidfVectorizer(analyzer = "word", max_df=0.5, ngram_range = (1, 3), max_features = 100000)),("classifier", LinearSVC())
])

Textpipeline.fit(data["sentence_preprocess_tag"], data["MOTIF_DISC"])

sklearn2pmml(Textpipeline,"TextMiningClassifier.pmml", with_repr = True)_

**Unfortunately, I keep having this message error :**

_Standard output is empty

---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-13-d92bb6908026> in <module>()
----> 1 sklearn2pmml(Textpipeline,"TextMiningClassifier.pmml", with_repr = True)

C:\ProgramData\Anaconda\lib\site-packages\sklearn2pmml\__init__.py in sklearn2pmml(pipeline, pmml, user_classpath, with_repr, debug)
    237                                 print("Standard output is empty")
    238                         if(len(error) > 0):
--> 239                                 print("Standard error:\n{0}".format(error.decode("UTF-8")))
    240                         else:
    241                                 print("Standard error is empty")

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 1: invalid continuation byte_

**Do you an idea about what could cause this error ?

Thanks,

Sylvain**

**Comment by vruusmann** [comment] 2018-12-07 15:11
Duplicate of https://github.com/jpmml/sklearn2pmml/issues/120

I wonder why this decodec error is becoming "popular" now? Maybe the latest Python or Scikit-Learn changed something.

**Closed by vruusmann** 2018-12-07 15:11 UTC

**Comment by vruusmann** [comment] 2018-12-07 15:52
It is the same problem - the Java process is producing output/error byte streams that cannot be decoded using the UTF-8 charset. In issue #120 it's because the output byte stream contains chinese characters; in this issue the error stream is containing non-UTF-8 characters.

The fix is exactly the same in both cases - need to detect and apply the correct charset instead of UTF-8.

**Comment by sylvainferrec** [comment] 2018-12-10 15:30
I found the solution.
I am on Windows 7 and the Java encoding was cp1252.
So I changed _"Standard error:\n{0}".format(error.decode("UTF-8")))"_ to _"decode('latin1')"_ in your code and it works fine.

Thanks

**Comment by vruusmann** [comment] 2018-12-10 18:47
@sylvainferrec Can you check what is your default Python character encoding:

```Python
import sys
print(sys.getdefaultencoding())
```

Does this print `latin1` (or `cp1252`) as well?
