### ISSUE TITLE
Datatype wrongly displayed for string variable in PMML

### ISSUE THREAD

**Issue by salmankhan05101987** [jpmml/sklearn2pmml#282] opened 2021-05-09 13:37 UTC
I have a string variable with datatype as object(dtpe('O')) in pandas dataframe. I am doing transformation of this variable and finally storing  result as float. But in the generated PMML at the initial few lines under DataDictionary -> DataField , its datatype is displayed as Double instead of string.

Eg: 
DataField dataType="double" name="variable_xyz" optype="continuous"

Could you please help how can we handle this scenario ?

**Comment by salmankhan05101987** [comment] 2021-05-09 13:38
Eg: 
<DataDictionary>
		<DataField dataType="double" name="variable_xyz" optype="continuous" />
		</DataField> 
</DataDictionary>

**Comment by salmankhan05101987** [comment] 2021-05-09 13:39
DataField dataType="double" name="variable_xyz" optype="continuous"

**Comment by vruusmann** [comment] 2021-05-09 17:11
Clsoing as exact duplicate of https://github.com/jpmml/sklearn2pmml/issues/280

Still no actionable information.

> DataField dataType="double" name="variable_xyz" optype="continuous"

LGTM

**Closed by vruusmann** 2021-05-09 17:11 UTC
