### ISSUE TITLE
PMML downgrade from 4.4 to 4.3

### ISSUE THREAD

**Issue by AraceliAL** [jpmml/sklearn2pmml#341] opened 2022-07-26 14:59 UTC
I would like to downgrade the PMML file from version 4.4 to 4.3. The thing is that to do so, It seems that I need **version 0.56 of sklearn2pmml** (see stackoverflow [here](https://stackoverflow.com/questions/69730527/downgrading-pmml-4-4-to-4-3-version)). But, Once running my code with this version, then the following error arises:

`AttributeError: 'PMMLPipeline' object has no attribute 'apply_transformer'`

And it seems, that to solve this last error I need **more updated versions** of sklearn2pmml (see [here](https://github.com/jpmml/sklearn2pmml/issues/261))

What should I do? I feel really trapped

**Comment by vruusmann** [comment] 2022-07-26 15:29
Closing as a functional duplicate of https://github.com/jpmml/sklearn2pmml/issues/260

**Closed by vruusmann** 2022-07-26 15:29 UTC
