### ISSUE TITLE
Sklearn Pipeline with XGBoost model cannot be saved

### ISSUE THREAD

**Issue by sneaxiy** [jpmml/sklearn2pmml#221] opened 2020-05-20 10:01 UTC
- XGBoost version: 1.1.0
- sklearn2pmml version: 0.56.1
- scikit-learn: 0.23.0

```python
from sklearn2pmml.pipeline import PMMLPipeline
from sklearn2pmml import sklearn2pmml
from xgboost import XGBClassifier
import numpy as np

Pipeline = PMMLPipeline

classifier = XGBClassifier()

pipeline = Pipeline([('classifer', classifier)])

X = np.array([[1, 2], [3, 4]])
y = np.array([0, 1])

pipeline.fit(X,y)

sklearn2pmml(pipeline, "XGBoost.pmml")
```

The code above raises the following errors:
```
java.lang.RuntimeException: java.io.IOException: Expected 27-element array of zeroes, got [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
	at xgboost.sklearn.Booster.loadLearner(Booster.java:54)
	at xgboost.sklearn.Booster.getLearner(Booster.java:42)
	at xgboost.sklearn.BoosterUtil.getLearner(BoosterUtil.java:71)
	at xgboost.sklearn.BoosterUtil.getNumberOfFeatures(BoosterUtil.java:39)
	at xgboost.sklearn.XGBClassifier.getNumberOfFeatures(XGBClassifier.java:35)
	at sklearn2pmml.pipeline.PMMLPipeline.initActiveFields(PMMLPipeline.java:525)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:215)
	at org.jpmml.sklearn.Main.run(Main.java:228)
	at org.jpmml.sklearn.Main.main(Main.java:148)
Caused by: java.io.IOException: Expected 27-element array of zeroes, got [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
	at org.jpmml.xgboost.XGBoostDataInput.readReserved(XGBoostDataInput.java:179)
	at org.jpmml.xgboost.Learner.load(Learner.java:82)
	at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:95)
	at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:57)
	at xgboost.sklearn.Booster.loadLearner(Booster.java:52)
	... 8 more

Exception in thread "main" java.lang.RuntimeException: java.io.IOException: Expected 27-element array of zeroes, got [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
	at xgboost.sklearn.Booster.loadLearner(Booster.java:54)
	at xgboost.sklearn.Booster.getLearner(Booster.java:42)
	at xgboost.sklearn.BoosterUtil.getLearner(BoosterUtil.java:71)
	at xgboost.sklearn.BoosterUtil.getNumberOfFeatures(BoosterUtil.java:39)
	at xgboost.sklearn.XGBClassifier.getNumberOfFeatures(XGBClassifier.java:35)
	at sklearn2pmml.pipeline.PMMLPipeline.initActiveFields(PMMLPipeline.java:525)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:215)
	at org.jpmml.sklearn.Main.run(Main.java:228)
	at org.jpmml.sklearn.Main.main(Main.java:148)
Caused by: java.io.IOException: Expected 27-element array of zeroes, got [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
	at org.jpmml.xgboost.XGBoostDataInput.readReserved(XGBoostDataInput.java:179)
	at org.jpmml.xgboost.Learner.load(Learner.java:82)
	at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:95)
	at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:57)
	at xgboost.sklearn.Booster.loadLearner(Booster.java:52)
	... 8 more
```

Could you help me find out why the error occurs?

**Comment by sneaxiy** [comment] 2020-05-20 10:05
I rollback xgboost from 1.1.0 to 1.0.0, and the error disappear. Maybe it is because the encoding way of xgboost 1.1.0 is incompatible with 1.0.0?

**Comment by vruusmann** [comment] 2020-05-20 16:22
Closing as an exact duplicate of https://github.com/jpmml/jpmml-xgboost/issues/48

Apparently, a new version of the XGBoost package has been released to PyPI earlier this week.

**Closed by vruusmann** 2020-05-20 16:22 UTC
