### ISSUE TITLE
imbalanced-learn package support

### ISSUE THREAD

**Issue by Alireza-Chakeri** [jpmml/sklearn2pmml#44] opened 2017-07-19 18:44 UTC
I am using imbalanced-learn package (part of scikit-learn-contrib projects) in order to balance the two classes by using SMOTE. I wanted to import my already fitted pipeline ("SMOTE_clf") into PMML to use it in Spark by simply writing:

```
my_pipeline = PMMLPipeline([
  ("estimator", SMOTE_clf)
])
sklearn2pmml(my_pipeline, "my_pipeline.pmml", with_repr = True)
```

but it gives me this error "The JPMML-SkLearn conversion application has failed. The Java process should have printed more information about the failure into its standard output and/or error streams"

is it because the pmml does not support the imbalanced-learn package?

**Comment by vruusmann** [comment] 2017-07-19 21:53
> it gives me this error "The JPMML-SkLearn conversion application has failed. The Java process should have printed more information about the failure into its standard output and/or error streams"

What did the Java process print to standard output and/or error streams?

> is it because the pmml does not support the imbalanced-learn package?

The detailed description of the error condition is in the logfile. I don't have access to your logfiles, you do.

**Comment by vruusmann** [comment] 2017-07-19 21:58
Possibly a duplicate of https://github.com/jpmml/sklearn2pmml/issues/23

**Closed by vruusmann** 2017-07-19 21:58 UTC
