### ISSUE TITLE
XGBoost to PMML fails for unknown reason

### ISSUE THREAD

**Issue by lctdulac** [jpmml/sklearn2pmml#278] opened 2021-04-23 14:51 UTC
Hi,

I have been training a XGBoost model and trying to convert it to PMML using your really cool project.

* Model has 78 features, all numeric, does contain NAs (XGB handle them)
* Model is already trained

`('model', XGBClassifier(base_score=0.156021345656599, booster='gbtree',
              colsample_bylevel=1, colsample_bynode=1,
              colsample_bytree=0.8855391962898097, gamma=2.5814868156775965,
              gpu_id=-1, importance_type='gain', interaction_constraints='',
              learning_rate=0.02, max_delta_step=0, max_depth=9,
              min_child_weight=7.0, missing=nan, monotone_constraints='()',
              n_estimators=2000, n_jobs=32, num_parallel_tree=1, random_state=0,
              reg_alpha=40, reg_lambda=0.41372764237878545, scale_pos_weight=1,
              subsample=0.9324999281738754, tree_method='exact',
              validate_parameters=1, verbosity=1))`

* Names all have the following format (strings) 'xxx_xxx_xx113'
* Model has been saved as a pickle file

* XGB version: 1.4.0
* sklearn2ppml version: 0.64.0
* sklearn_pandas version: 2.0.3

I'm trying two different setup and both fails, which I can't figure out why.

```
### Setup 1 : just the model

# define the pipeline
pmml_pipeline = PMMLPipeline([
    ("model", final_model) # final_model is my XGBClassifier() instance, which works fine with predict
])

pmml_pipeline.active_fields = np.array(var_features)

# verify the pipeline
pmml_pipeline.verify(X_train_reduced.sample(n = 10)) # works (doesn't return anything)

# save PMML [Fails]
sklearn2pmml.sklearn2pmml(pmml_pipeline, "XGB_binary.pmml")```

And there it fails, which I don't get why : 

Standard output is empty
Standard error:
Apr 23, 2021 2:44:28 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Apr 23, 2021 2:44:28 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 66 ms.
Apr 23, 2021 2:44:28 PM org.jpmml.sklearn.Main run
INFO: Converting PKL to PMML..
Apr 23, 2021 2:44:28 PM sklearn2pmml.pipeline.PMMLPipeline initTargetFields
WARNING: Attribute 'sklearn2pmml.pipeline.PMMLPipeline.target_fields' is not set. Assuming y as the name of the target field
Apr 23, 2021 2:44:28 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert PKL to PMML
java.lang.IllegalArgumentException: 1730313018.1919250021
	at org.jpmml.xgboost.Learner.load(Learner.java:81)
	at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:93)
	at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:57)
	at xgboost.sklearn.Booster.loadLearner(Booster.java:52)
	at xgboost.sklearn.Booster.getLearner(Booster.java:42)
	at xgboost.sklearn.BoosterUtil.getLearner(BoosterUtil.java:71)
	at xgboost.sklearn.BoosterUtil.getNumberOfFeatures(BoosterUtil.java:39)
	at xgboost.sklearn.XGBClassifier.getNumberOfFeatures(XGBClassifier.java:35)
	at sklearn.StepUtil.checkNumberOfFeatures(StepUtil.java:36)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:229)
	at org.jpmml.sklearn.Main.run(Main.java:233)
	at org.jpmml.sklearn.Main.main(Main.java:151)

Exception in thread "main" java.lang.IllegalArgumentException: 1730313018.1919250021
	at org.jpmml.xgboost.Learner.load(Learner.java:81)
	at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:93)
	at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:57)
	at xgboost.sklearn.Booster.loadLearner(Booster.java:52)
	at xgboost.sklearn.Booster.getLearner(Booster.java:42)
	at xgboost.sklearn.BoosterUtil.getLearner(BoosterUtil.java:71)
	at xgboost.sklearn.BoosterUtil.getNumberOfFeatures(BoosterUtil.java:39)
	at xgboost.sklearn.XGBClassifier.getNumberOfFeatures(XGBClassifier.java:35)
	at sklearn.StepUtil.checkNumberOfFeatures(StepUtil.java:36)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:229)
	at org.jpmml.sklearn.Main.run(Main.java:233)
	at org.jpmml.sklearn.Main.main(Main.java:151)

## Setup 2 : scaling+model

# define the mapping
var_cols = [
    (
        [v], [ContinuousDomain(),
              SimpleImputer(),
              StandardScaler()
              ]
    ) for v in var_features
]

mapper = DataFrameMapper(var_cols, default=False)

# define the pipeline
pmml_pipeline = PMMLPipeline([
    ("mapper", mapper),
    ("model", final_model) # final_model is my XGBClassifier() instance
])

pmml_pipeline.active_fields = np.array(var_features)

# verify the pipeline [Fails : returns AttributeError: 'DataFrameMapper' object has no attribute 'built_features']
pmml_pipeline.verify(X_train_reduced.sample(n = 10))

# save PMML [Fails]
sklearn2pmml.sklearn2pmml(pmml_pipeline, "XGB_binary.pmml")

Also: 

Standard output is empty
Standard error:
Apr 23, 2021 2:50:49 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Apr 23, 2021 2:50:49 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 86 ms.
Apr 23, 2021 2:50:49 PM org.jpmml.sklearn.Main run
INFO: Converting PKL to PMML..
Apr 23, 2021 2:50:49 PM sklearn2pmml.pipeline.PMMLPipeline initTargetFields
WARNING: Attribute 'sklearn2pmml.pipeline.PMMLPipeline.target_fields' is not set. Assuming y as the name of the target field
Apr 23, 2021 2:50:49 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert PKL to PMML
java.lang.IllegalArgumentException: The value of 'sklearn2pmml.decoration.ContinuousDomain.data_min_' attribute (null) is not a supported array type
	at org.jpmml.python.PythonObject.getArrayShape(PythonObject.java:244)
	at sklearn2pmml.decoration.ContinuousDomain.getArrayShape(ContinuousDomain.java:162)
	at org.jpmml.python.PythonObject.getArrayShape(PythonObject.java:248)
	at sklearn2pmml.decoration.ContinuousDomain.getDataMinShape(ContinuousDomain.java:189)
	at sklearn2pmml.decoration.ContinuousDomain.getNumberOfFeatures(ContinuousDomain.java:51)
	at sklearn.StepUtil.checkNumberOfFeatures(StepUtil.java:36)
	at sklearn.Transformer.encode(Transformer.java:66)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:73)
	at sklearn.Initializer.encodeFeatures(Initializer.java:48)
	at sklearn.Transformer.encode(Transformer.java:70)
	at sklearn.Composite.encodeFeatures(Composite.java:119)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:210)
	at org.jpmml.sklearn.Main.run(Main.java:233)
	at org.jpmml.sklearn.Main.main(Main.java:151)

Exception in thread "main" java.lang.IllegalArgumentException: The value of 'sklearn2pmml.decoration.ContinuousDomain.data_min_' attribute (null) is not a supported array type
	at org.jpmml.python.PythonObject.getArrayShape(PythonObject.java:244)
	at sklearn2pmml.decoration.ContinuousDomain.getArrayShape(ContinuousDomain.java:162)
	at org.jpmml.python.PythonObject.getArrayShape(PythonObject.java:248)
	at sklearn2pmml.decoration.ContinuousDomain.getDataMinShape(ContinuousDomain.java:189)
	at sklearn2pmml.decoration.ContinuousDomain.getNumberOfFeatures(ContinuousDomain.java:51)
	at sklearn.StepUtil.checkNumberOfFeatures(StepUtil.java:36)
	at sklearn.Transformer.encode(Transformer.java:66)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:73)
	at sklearn.Initializer.encodeFeatures(Initializer.java:48)
	at sklearn.Transformer.encode(Transformer.java:70)
	at sklearn.Composite.encodeFeatures(Composite.java:119)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:210)
	at org.jpmml.sklearn.Main.run(Main.java:233)
	at org.jpmml.sklearn.Main.main(Main.java:151)```


Do you know what I might be doing wrong? 

Thank you,
Lance

**Comment by vruusmann** [comment] 2021-04-23 16:11
> java.lang.IllegalArgumentException: 1730313018.1919250021

This issue is an exact duplicate of https://github.com/jpmml/jpmml-xgboost/issues/54

> sklearn2ppml version: 0.64.0

The first JSON-aware Sklearn2PMML package version is 0.69.0. 

> Do you know what I might be doing wrong? 

You could improve a bit in the following areas:

1. Always upgrade to the latest SkLearn2PMML version before troubleshooting conversion errors.
2. Ask Google about the exception message. This XGBoost 1.2.X -> 1.3.X has a very characteristic exception message.

**Closed by vruusmann** 2021-04-23 16:11 UTC

**Comment by vruusmann** [comment] 2021-04-23 16:16
> java.lang.IllegalArgumentException: The value of 'sklearn2pmml.decoration.ContinuousDomain.data_min_' attribute (null) is not a supported array type

You have to fit  domain decorator classes before converting.

Right now you've created a pipeline using estimators that are inconsistently initialized (some are fitted, some are not fitted).
