### ISSUE TITLE
Schema and version parameters do not match

### ISSUE THREAD

**Issue by JasonCRodriguez** [jpmml/sklearn2pmml#243] opened 2020-09-01 21:25 UTC
The resulting pmml contains the following which causes an error on import:
\<PMML xmlns="http://www.dmg.org/PMML-4_4" xmlns:data="http://jpmml.org/jpmml-model/InlineTable" version="4.3"\>

Shouldn't it be:
\<PMML xmlns="http://www.dmg.org/PMML-4_4" xmlns:data="http://jpmml.org/jpmml-model/InlineTable" version="**4.4**"\>

Here's an example of what the pmml file should look like [file](https://github.com/jpmml/sklearn2pmml/files/5158922/RidgeRegression.txt). This file does not cause import errors in the target program.

The pmml was generated using sklearn2pmml version 1.6.4

Thanks!

**Comment by vruusmann** [comment] 2020-09-02 16:52
Closing as duplicate of https://github.com/jpmml/jpmml-converter/issues/18

Has been fixed in https://github.com/jpmml/jpmml-converter/commit/ca135aaa8c5afcd5b42ff53abbb708b586dd0a64. However, the update has not been released yet.

> This file does not cause import errors in the target program.

Sure, the PMML@version attribute is for information purposes. It should not affect the consumer in any way.

**Closed by vruusmann** 2020-09-02 16:52 UTC

**Comment by TigerTigerWoods** [comment] 2020-09-03 14:51
We use the schema to verify the file. We verify that the schema and version specified match - if they don't we prefer not to trust the file.
