### ISSUE TITLE
Change name of features

### ISSUE THREAD

**Issue by sharonzagh** [jpmml/sklearn2pmml#255] opened 2020-10-26 18:25 UTC
Hi, 
I want to create a DataFrameMapper with many transformations on different features and in the end I want to replace special characters in the name of the created features by the DataFrameMapper 
How can I do to access those features  ?

**Comment by vruusmann** [comment] 2020-10-26 18:48
IIRC, I gave a very detailed explanation about renaming features in one of those issues that you asked me to delete later.

So, look into your mail archive.

**Comment by sharonzagh** [comment] 2020-10-26 19:25
Hi,
I don't know what you are talking about, could you send me the link of the closed issue maybe

**Comment by vruusmann** [comment] 2020-10-26 19:40
> could you send me the link of the closed issue maybe

Was in one of them: https://github.com/jpmml/sklearn2pmml/issues/246 or https://github.com/jpmml/sklearn2pmml/issues/249

**Comment by sharonzagh** [comment] 2020-10-26 19:45
Hi,
I don't have any of those tickets in my mail so maybe you confused with
someone else
Could you explain me please, I really want to understand

Le lun. 26 oct. 2020 à 21:41, Villu Ruusmann <notifications@github.com> a
écrit :

**Comment by vruusmann** [comment] 2020-10-28 19:35
Closing as exact duplicate of jpmml/sklearn2pmml#249

**Closed by vruusmann** 2020-10-28 19:35 UTC
