### ISSUE TITLE
Support for sklearn ensemble models

### ISSUE THREAD

**Issue by jche318** [jpmml/sklearn2pmml#121] opened 2018-12-06 01:56 UTC
I read sklearn2pmml is made to be compatible for sklearn **core** models, meanwhile the jpmml.sklearn readme notes that sklearn.ensemble models specifically the RandomForestRegressor() is supported.

I could get my code to marshall pmml using sklearn.linear_model LinearRegression() meanwhile making slight tweaks for the RandomForestRegressor() fails at parsing the pickle. Is this expected?
[base_model_pmml_test.zip](https://github.com/jpmml/sklearn2pmml/files/2651829/base_model_pmml_test.zip)

Python 3.6.1
scikit-learn       0.20.1
sklearn2pmml       0.39.0

```
Dec. 06, 2018 4:48:57 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Dec. 06, 2018 4:48:57 PM org.jpmml.sklearn.Main run
SEVERE: Failed to parse PKL 
net.razorvine.pickle.InvalidOpcodeException: invalid pickle opcode: 0
	at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:355)
	at org.jpmml.sklearn.PickleUtil$1.dispatch(PickleUtil.java:77)
	at net.razorvine.pickle.Unpickler.load(Unpickler.java:122)
	at org.jpmml.sklearn.PickleUtil.unpickle(PickleUtil.java:98)
	at org.jpmml.sklearn.Main.run(Main.java:104)
	at org.jpmml.sklearn.Main.main(Main.java:94)
Exception in thread "main" net.razorvine.pickle.InvalidOpcodeException: invalid pickle opcode: 0
	at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:355)
	at org.jpmml.sklearn.PickleUtil$1.dispatch(PickleUtil.java:77)
	at net.razorvine.pickle.Unpickler.load(Unpickler.java:122)
	at org.jpmml.sklearn.PickleUtil.unpickle(PickleUtil.java:98)
	at org.jpmml.sklearn.Main.run(Main.java:104)
	at org.jpmml.sklearn.Main.main(Main.java:94)
```

**Comment by vruusmann** [comment] 2018-12-06 09:22
The up-to-date list of supported Scikit-Learn model types is given here: https://github.com/jpmml/jpmml-sklearn#features

There's a decent coverage of `sklearn.ensemble` estimator types, including `sklearn.ensemble.RandomForestClassifier` and `sklearn.ensemble.RandomForestRegressor` classes.

By saying "core", I mean estimator types that are part of the official Scikit-Learn package/distribution (ie. classes that you get when doing `pip install scikit-learn`). The SkLearn2PMML/JPMML-SkLearn stack can be made to support most "non-core" aka "extension" packages as well. However, I need a clearly motivated feature request coming in, because I don't have time/resources to watch all the development activity around the Scikit-Learn package myself.

**Comment by jche318** [comment] 2018-12-06 21:32
Hi vruusmann,

PFA a zip containing my pickle **pipeline-g9oukg4n.pkl.z** from my above run

[pipeline-g9oukg4n.pkl.zip](https://github.com/jpmml/sklearn2pmml/files/2654980/pipeline-g9oukg4n.pkl.zip)

**Comment by vruusmann** [comment] 2018-12-06 22:04
@jche318 Can confirm that your pipeline Pickle file throws an `net.razorvine.pickle.InvalidOpcodeException` exception in my computer too.

The zero byte (`0`) is not a valid pickle opcode. Therefore, I suspect that the byte stream is encoded in some way; perhaps it has not been uncompressed properly/fully?

Can you tell me your `sklearn.externals.joblib` package version as well?

**Comment by vruusmann** [comment] 2018-12-06 22:05
> Can you tell me your sklearn.externals.joblib package version as well?

```Python
from sklearn.externals import joblib
print(joblib.__version__)
```

**Comment by jche318** [comment] 2018-12-06 22:21
joblib 0.13.0
I also notice re-running the same code above sometimes gives an alternative opcode: 254. Sometimes 0.
Any ideas?

```
Standard error:
Dec. 07, 2018 9:15:54 AM org.jpmml.sklearn.Main run

INFO: Parsing PKL..

Dec. 07, 2018 9:15:55 AM org.jpmml.sklearn.Main run

SEVERE: Failed to parse PKL

net.razorvine.pickle.InvalidOpcodeException: invalid pickle opcode: 254

	at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:355)

	at org.jpmml.sklearn.PickleUtil$1.dispatch(PickleUtil.java:77)

	at net.razorvine.pickle.Unpickler.load(Unpickler.java:122)

	at org.jpmml.sklearn.PickleUtil.unpickle(PickleUtil.java:98)

	at org.jpmml.sklearn.Main.run(Main.java:104)

	at org.jpmml.sklearn.Main.main(Main.java:94)



Exception in thread "main" net.razorvine.pickle.InvalidOpcodeException: invalid pickle opcode: 254

	at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:355)

	at org.jpmml.sklearn.PickleUtil$1.dispatch(PickleUtil.java:77)

	at net.razorvine.pickle.Unpickler.load(Unpickler.java:122)

	at org.jpmml.sklearn.PickleUtil.unpickle(PickleUtil.java:98)

	at org.jpmml.sklearn.Main.run(Main.java:104)

	at org.jpmml.sklearn.Main.main(Main.java:94)

```

**Comment by vruusmann** [comment] 2018-12-06 23:10
> re-running the same code above sometimes gives an alternative opcode: 254. Sometimes 0.

That doesn't make sense at all - the pickling process should be fully deterministic, which means that it should give a byte-wise identical file each time.

This issue is probably related to Python version (changes to Pickle protocol), Numpy version (changes to Numpy array serialization format) or Scikit-Learn's Joblib module version (changes to object splitting logic - one object becomes many small objects during serialization).

In your Python script you have `LinearRegressor` as well. Does the script keep failing with `InvalidOpcodeException` if you replace `RandomForestRegressor` with `LinearRegressor` temporarily? It should fail if this issue is related to Python or Numpy version; it should succeed if this issue is related to Scikit-Learn's Joblib module version (linear regression object is split differently than random forest object).

By any chance, do you have some older Python version (eg. 2.7.X) installed in your computer? What happens if you execute your script with it?

**Comment by jche318** [comment] 2018-12-06 23:48
If I switch to the LinearRegressor, the pmml pipeline works successfully. Which leads me to believe it's the latter of your suggestion re: Joblib?

**Comment by vruusmann** [comment] 2018-12-07 07:58
I suspect it is a model picking issue, which is related to the `sklearn.externals.joblib` package/module version. The `LinearRegressor` class contains one simple matrix that is easy to serialize. The `RandomForestRegressor` class contains many complex matrices, and something gets broken there (ie. resulting invalid pickle opcodes to be written out).

To confirm this hypothesis, can you check if `sklearn.ensemble.GradientBoostingRegressor` and `sklearn.ensemble.IsolationForest` are also failing or not?

Of course, there's a very small chance that the Scikit-Learn's Joblib issue is specific to your computer, and works fine for everybody else in the world. That's why you should check with a different Python/Scikit-Learn version locally if you have a chance to do so.

**Comment by jche318** [comment] 2018-12-10 00:06
Using **GradientBoostingRegressor**, successfully unpickled but some issue with identifying active/target fields.
```
import sklearn.datasets
from sklearn.linear_model import LinearRegression
from sklearn2pmml.pipeline import PMMLPipeline
from sklearn2pmml import sklearn2pmml
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import IsolationForest
data=sklearn.datasets.load_iris()
X=data["data"]
y=data["target"]
pipeline_model = PMMLPipeline([("regression",GradientBoostingRegressor())])
pipeline_model.fit(X,y)
sklearn2pmml(pipeline_model,"model_gradboost.pmml", with_repr = True, debug=True)
[pipeline-juasn0zx.pkl.zip]

```

```
Standard error:
Dec. 10, 2018 11:02:56 AM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Dec. 10, 2018 11:02:56 AM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 168 ms.
Dec. 10, 2018 11:02:56 AM org.jpmml.sklearn.Main run
INFO: Converting..
Dec. 10, 2018 11:02:56 AM sklearn2pmml.pipeline.PMMLPipeline encodePMML
WARNING: Attribute 'sklearn2pmml.pipeline.PMMLPipeline.target_fields' is not set. Assuming y as the name of the target field
Dec. 10, 2018 11:02:56 AM sklearn2pmml.pipeline.PMMLPipeline initFeatures
WARNING: Attribute 'sklearn2pmml.pipeline.PMMLPipeline.active_fields' is not set. Assuming [x1, x2, x3, x4] as the names of active fields
Dec. 10, 2018 11:02:56 AM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.ArrayIndexOutOfBoundsException: 50
```
[pipeline-juasn0zx.pkl.zip](https://github.com/jpmml/sklearn2pmml/files/2661163/pipeline-juasn0zx.pkl.zip)


**IsolationForest** had a pickle parsing error
Standard error:
```
Dec. 10, 2018 10:59:30 AM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Dec. 10, 2018 10:59:30 AM org.jpmml.sklearn.Main run
SEVERE: Failed to parse PKL
net.razorvine.pickle.InvalidOpcodeException: invalid pickle opcode: 0
	at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:355)
	at org.jpmml.sklearn.PickleUtil$1.dispatch(PickleUtil.java:77)
	at net.razorvine.pickle.Unpickler.load(Unpickler.java:122)
	at org.jpmml.sklearn.PickleUtil.unpickle(PickleUtil.java:98)
	at org.jpmml.sklearn.Main.run(Main.java:104)
	at org.jpmml.sklearn.Main.main(Main.java:94)
Exception in thread "main" net.razorvine.pickle.InvalidOpcodeException: invalid pickle opcode: 0
	at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:355)
	at org.jpmml.sklearn.PickleUtil$1.dispatch(PickleUtil.java:77)
	at net.razorvine.pickle.Unpickler.load(Unpickler.java:122)
	at org.jpmml.sklearn.PickleUtil.unpickle(PickleUtil.java:98)
	at org.jpmml.sklearn.Main.run(Main.java:104)
	at org.jpmml.sklearn.Main.main(Main.java:94)
Preserved joblib dump file(s): C:\Users\jc\AppData\Local\Temp\pipeline-8cc2ddhx.pkl.z
```
[pipeline-8cc2ddhx.pkl.zip](https://github.com/jpmml/sklearn2pmml/files/2661159/pipeline-8cc2ddhx.pkl.zip)

**Comment by vruusmann** [comment] 2018-12-10 10:03
I've just upgraded JPMML-SkLearn integration tests to Scikit-Learn version 0.20.1, which includes `sklearn.externals.joblib` version 0.13.0. All integration tests execute and pass cleanly.

That leads me to believe that there is something wrong with your local Scikit-Learn setup. If the SkLearn2PMML/JPMML-SkLearn had serious problems parsing `RandomForestRegregressor` pickle files, then there would be many-many other bug reports open here already.

**Comment by vruusmann** [comment] 2018-12-10 10:05
```Python
data=sklearn.datasets.load_iris()
X=data["data"]
y=data["target"]
```

In the above code, `X` and `y` are plain Numpy matrices, which do not contain any column identifiers - that's why the converter is issuing a warning that it's using default column names (`x1`, `x2`, .., `xn`, and `y`, respectively).

You should replace Numpy matrices with `pandas.DataFrame` if possible.

**Comment by vruusmann** [comment] 2018-12-10 10:07
> All integration tests execute and pass cleanly.

Based on the above observation, I close this issue as irreproducible/unfixable.

**Closed by vruusmann** 2018-12-10 10:07 UTC
