### ISSUE TITLE
xgboost with simple sklearn pipeline raises java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by elad663** [jpmml/sklearn2pmml#270] opened 2021-03-08 11:13 UTC
hi,

when constructing a simple sklearn pipline
```
default_mapper = DataFrameMapper([(i, None) for i in vars])
pipeline = PMMLPipeline([
    ("mapper", default_mapper),
    ("classifier", XGBClassifier(**pars,n_jobs=-1))
])
```

...(data is loaded, model is fitted)...

`sklearn2pmml(pipeline, 'pmml_test.pmml', debug = True)`

> python: 3.7.2
> sklearn: 0.24.1
> sklearn2pmml: 0.68.0
> joblib: 1.0.1
> sklearn_pandas: 2.1.0
> pandas: 1.1.5
> numpy: 1.19.4
> java: N/A
> Executing command:
> java -cp C:\Users\admin1\.pyenv\pyenv-win\versions\3.7.2\lib\site-packages\sklearn2pmml\resources\gson-2.6.2.jar;C:\Users\admin1\.pyenv\pyenv-win\versions\3.7.2\lib\site-packages\sklearn2pmml\resources\guava-21.0.jar;C:\Users\admin1\.pyenv\pyenv-win\versions\3.7.2\lib\site-packages\sklearn2pmml\resources\h2o-genmodel-3.32.0.4.jar;C:\Users\admin1\.pyenv\pyenv-win\versions\3.7.2\lib\site-packages\sklearn2pmml\resources\h2o-logger-3.32.0.4.jar;C:\Users\admin1\.pyenv\pyenv-win\versions\3.7.2\lib\site-packages\sklearn2pmml\resources\h2o-tree-api-0.3.17.jar;C:\Users\admin1\.pyenv\pyenv-win\versions\3.7.2\lib\site-packages\sklearn2pmml\resources\istack-commons-runtime-3.0.11.jar;C:\Users\admin1\.pyenv\pyenv-win\versions\3.7.2\lib\site-packages\sklearn2pmml\resources\jakarta.activation-1.2.2.jar;C:\Users\admin1\.pyenv\pyenv-win\versions\3.7.2\lib\site-packages\sklearn2pmml\resources\jakarta.xml.bind-api-2.3.3.jar;C:\Users\admin1\.pyenv\pyenv-win\versions\3.7.2\lib\site-packages\sklearn2pmml\resources\jaxb-runtime-2.3.3.jar;C:\Users\admin1\.pyenv\pyenv-win\versions\3.7.2\lib\site-packages\sklearn2pmml\resources\jcommander-1.72.jar;C:\Users\admin1\.pyenv\pyenv-win\versions\3.7.2\lib\site-packages\sklearn2pmml\resources\jpmml-converter-1.4.6.jar;C:\Users\admin1\.pyenv\pyenv-win\versions\3.7.2\lib\site-packages\sklearn2pmml\resources\jpmml-h2o-1.1.4.jar;C:\Users\admin1\.pyenv\pyenv-win\versions\3.7.2\lib\site-packages\sklearn2pmml\resources\jpmml-lightgbm-1.3.6.jar;C:\Users\admin1\.pyenv\pyenv-win\versions\3.7.2\lib\site-packages\sklearn2pmml\resources\jpmml-python-1.0.11.jar;C:\Users\admin1\.pyenv\pyenv-win\versions\3.7.2\lib\site-packages\sklearn2pmml\resources\jpmml-sklearn-1.6.14.jar;C:\Users\admin1\.pyenv\pyenv-win\versions\3.7.2\lib\site-packages\sklearn2pmml\resources\jpmml-xgboost-1.4.5.jar;C:\Users\admin1\.pyenv\pyenv-win\versions\3.7.2\lib\site-packages\sklearn2pmml\resources\pickle-1.1.jar;C:\Users\admin1\.pyenv\pyenv-win\versions\3.7.2\lib\site-packages\sklearn2pmml\resources\pmml-model-1.5.11.jar;C:\Users\admin1\.pyenv\pyenv-win\versions\3.7.2\lib\site-packages\sklearn2pmml\resources\pmml-model-metro-1.5.11.jar;C:\Users\admin1\.pyenv\pyenv-win\versions\3.7.2\lib\site-packages\sklearn2pmml\resources\serpent-1.30.jar;C:\Users\admin1\.pyenv\pyenv-win\versions\3.7.2\lib\site-packages\sklearn2pmml\resources\slf4j-api-1.7.30.jar;C:\Users\admin1\.pyenv\pyenv-win\versions\3.7.2\lib\site-packages\sklearn2pmml\resources\slf4j-jdk14-1.7.30.jar org.jpmml.sklearn.Main --pkl-pipeline-input C:\Users\admin1\AppData\Local\Temp\2\pipeline-bwdlr4rd.pkl.z --pmml-output xss2pmml_test.pmml
> Standard output is empty
> Standard error:
> Mar 08, 2021 10:57:16 AM org.jpmml.sklearn.Main run
> INFO: Parsing PKL..
> Mar 08, 2021 10:57:16 AM org.jpmml.sklearn.Main run
> INFO: Parsed PKL in 31 ms.
> Mar 08, 2021 10:57:16 AM org.jpmml.sklearn.Main run
> INFO: Converting PKL to PMML..
> Mar 08, 2021 10:57:16 AM org.jpmml.sklearn.Main run
> SEVERE: Failed to convert PKL to PMML
> java.lang.IllegalArgumentException: 1730313018.1919250021
> 	at org.jpmml.xgboost.Learner.load(Learner.java:82)
> 	at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:93)
> 	at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:57)
> 	at xgboost.sklearn.Booster.loadLearner(Booster.java:52)
> 	at xgboost.sklearn.Booster.getLearner(Booster.java:42)
> 	at xgboost.sklearn.BoosterUtil.getLearner(BoosterUtil.java:71)
> 	at xgboost.sklearn.BoosterUtil.getNumberOfFeatures(BoosterUtil.java:39)
> 	at xgboost.sklearn.XGBClassifier.getNumberOfFeatures(XGBClassifier.java:35)
> 	at sklearn.StepUtil.checkNumberOfFeatures(StepUtil.java:36)
> 	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:231)
> 	at org.jpmml.sklearn.Main.run(Main.java:233)
> 	at org.jpmml.sklearn.Main.main(Main.java:151)
> Exception in thread "main" java.lang.IllegalArgumentException: 1730313018.1919250021
> 	at org.jpmml.xgboost.Learner.load(Learner.java:82)
> 	at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:93)
> 	at org.jpmml.xgboost.XGBoostUtil.loadLearner(XGBoostUtil.java:57)
> 	at xgboost.sklearn.Booster.loadLearner(Booster.java:52)
> 	at xgboost.sklearn.Booster.getLearner(Booster.java:42)
> 	at xgboost.sklearn.BoosterUtil.getLearner(BoosterUtil.java:71)
> 	at xgboost.sklearn.BoosterUtil.getNumberOfFeatures(BoosterUtil.java:39)
> 	at xgboost.sklearn.XGBClassifier.getNumberOfFeatures(XGBClassifier.java:35)

`sinfo.sinfo()`
> pandas              1.1.5
> pypmml              0.9.7
> sinfo               0.3.1
> sklearn2pmml        0.68.0
> sklearn_pandas      2.1.0
> xgboost             1.3.3
> Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]
> Windows-10-10.0.14393-SP0
> 40 logical CPU cores, Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
> Session information updated at 2021-03-08 11:10

I tried to use only one variable, still the same error. I also tried fitting the xgb without any params, still the same.

**Comment by vruusmann** [comment] 2021-03-08 18:42
Closing as exact duplicate of https://github.com/jpmml/jpmml-xgboost/issues/54

**Closed by vruusmann** 2021-03-08 18:42 UTC
