### ISSUE TITLE
Different results for pmml and LightGBM

### ISSUE THREAD

**Issue by artakhm** [jpmml/sklearn2pmml#301] opened 2021-09-15 10:49 UTC
Hi,

It seems that having missing values makes pmml answers diverge from original LightGBM model predictions. Even though PMMLpipeline in python still makes the same predictions as model. There definately were missing values in training data, so I guess that https://github.com/jpmml/sklearn2pmml/issues/297 is not the case. I found out that prediction differs for objects with missing value in 'feat32' column

The pmml file was generated like this:
```
score_mapper = DataFrameMapper([([feat] , [ContinuousDomain(invalid_value_treatment='as_is')]) for feat in feats], input_df=True, df_out=True)
score_mapper.fit(df_tmp)

mapper = ColumnTransformer([
    (feature, Alias(ExpressionTransformer('X[0]'), feature+'_trans'), [feature]) for feature in feats[:-1]
])
mapper.fit(score_mapper.transform(df_tmp))

pipe_boost = PMMLPipeline([('mapper', mapper),('boosting', boost)])

steps = [
    ('seg', pipe_boost, 'X[35]==1')
]

pipe_conditional = PMMLPipeline([('mapper', score_mapper),
                                     ('conditional_pipeline',
                                      SelectFirstClassifier(steps))])

sklearn2pmml(pipe_conditional, 'model_file.pmml')
```
I run the pmml file with
`java -jar pmml-evaluator-example-executable.jar --model mode_file.pmml --input data.csv --output output.csv `

I've attached example of the data and the model. The 'model' columns in data stands for original LightGBM predictions
[model.zip](https://github.com/jpmml/sklearn2pmml/files/7169328/model.zip)
[data.csv](https://github.com/jpmml/sklearn2pmml/files/7169326/data.csv)

**Comment by vruusmann** [comment] 2021-09-15 20:25
Closing as a very likely duplicate of https://github.com/jpmml/jpmml-lightgbm/issues/51

What's the fuss about LightGBM and missing values in these days? Full moon or something?

**Closed by vruusmann** 2021-09-15 20:25 UTC
