### ISSUE TITLE
Unpickling error: invalid pickle opcode: 64

### ISSUE THREAD

**Issue by lanze0000** [jpmml/sklearn2pmml#378] opened 2023-04-23 05:10 UTC
Hello, I am encountering an issue where I am unable to generate PMML files from the MultiOutputClassifier estimator. When I tried using a single output classifier, I did not encounter any errors. However, after changing y to be multi-output, I started to get errors. The specific code and error message are as follows: 
```
from sklearn.datasets import make_multilabel_classification
from sklearn.multioutput import MultiOutputClassifier, MultiOutputRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn2pmml import PMMLPipeline
from sklearn2pmml.decoration import ContinuousDomain
from sklearn.preprocessing import StandardScaler
from sklearn2pmml import sklearn2pmml
import pandas as pd

X, y = make_multilabel_classification(n_samples=100, n_features=10, n_classes=3, random_state=1)


classifier = MultiOutputClassifier(DecisionTreeClassifier())

pipeline = PMMLPipeline([
    ("scaler", StandardScaler()),
    ("classifier", classifier)
])

pipeline.fit(X, y)

sklearn2pmml(pipeline, "iris_knn.pmml", with_repr=True, debug=True)
```
And I got:
```
python: 3.10.10
sklearn: 1.1.1
sklearn2pmml: 0.85.0
joblib: 1.2.0
sklearn_pandas: 2.2.0
pandas: 1.5.3
numpy: 1.24.2
openjdk: 17.0.3
Executing command:
java -cp d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\sklearn2pmml-1.0-SNAPSHOT.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\gson-2.9.0.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\guava-21.0.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\h2o-genmodel-3.36.1.3.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\h2o-logger-3.36.1.3.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\h2o-tree-api-0.3.17.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\istack-commons-runtime-4.0.1.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\jackson-annotations-2.13.1.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\jakarta.activation-2.0.1.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\jakarta.xml.bind-api-3.0.1.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\jaxb-core-3.0.2.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\jaxb-runtime-3.0.2.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\jcommander-1.72.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\pickle-1.3.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\pmml-converter-1.5.3.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\pmml-h2o-1.2.4.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\pmml-lightgbm-1.4.3.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\pmml-model-1.6.3.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\pmml-model-metro-1.6.3.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\pmml-python-1.1.6.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\pmml-sklearn-1.7.10.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\pmml-sklearn-extension-1.7.10.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\pmml-sklearn-h2o-1.7.10.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\pmml-sklearn-lightgbm-1.7.10.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\pmml-sklearn-xgboost-1.7.10.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\pmml-xgboost-1.7.0.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\serpent-1.40.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\slf4j-api-1.7.36.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\slf4j-jdk14-1.7.36.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\ubjson-0.1.8.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\ubjson-gson-0.1.8.jar com.sklearn2pmml.Main --pkl-pipeline-input C:\Users\lanze\AppData\Local\Temp\pipeline-3yip__hq.pkl.z --pmml-output iris_knn.pmml
Standard output is empty
Standard error:
Exception in thread "main" net.razorvine.pickle.InvalidOpcodeException: invalid pickle opcode: 64
	at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:366)
	at org.jpmml.python.CustomUnpickler.dispatch(CustomUnpickler.java:31)
	at org.jpmml.python.PickleUtil$1.dispatch(PickleUtil.java:64)
	at net.razorvine.pickle.Unpickler.load(Unpickler.java:109)
	at org.jpmml.python.PickleUtil.unpickle(PickleUtil.java:85)
	at com.sklearn2pmml.Main.run(Main.java:71)
	at com.sklearn2pmml.Main.main(Main.java:62)

Preserved joblib dump file(s): [C:\Users\lanze\AppData\Local\Temp\pipeline-3yip__hq.pkl.z](file:///C:/Users/lanze/AppData/Local/Temp/pipeline-3yip__hq.pkl.z)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[10], line 21
     14 pipeline = PMMLPipeline([
     15     ("scaler", StandardScaler()),
     16     ("classifier", classifier)
     17 ])
     19 pipeline.fit(X, y)
---> 21 sklearn2pmml(pipeline, "iris_knn.pmml", with_repr=True, debug=True)

File [d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\__init__.py:259](file:///D:/Anaconda3/envs/pycaret3/lib/site-packages/sklearn2pmml/__init__.py:259), in sklearn2pmml(pipeline, pmml, user_classpath, with_repr, debug)
    257 			print("Standard error is empty")
    258 	if retcode:
--> 259 		raise RuntimeError("The SkLearn2PMML application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
    260 finally:
    261 	if debug:

RuntimeError: The SkLearn2PMML application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
```

**Comment by vruusmann** [comment] 2023-04-23 05:50
This error is raised by a low-level Pickle library, which is responsible by parsing the pickle data file. It has got nothing to do with the SkLearn or PMML layers.

> sklearn2pmml: 0.85.0
> joblib: 1.2.0

For starters, update your SkLearn2PMML package version to latest.

I can remember fixing a Joblib compatibility issue within a ~past year.

Then, please report back if the unpickling error persists or not. If it does, then please attach a sample pickle file (for example, based on the DecisionTreeClassifier + Iris combo). I'd like to see such an invalid pickle file myself.

Over here, everything works flawlessly.

**Comment by lanze0000** [comment] 2023-04-23 07:50
Hi, thank you very much for your response. I'm still confused about how to modify pickle. I tried updating sklearn2pmml to version 0.92.0 and the previous issue disappeared, but a new problem emerged. I looked up some information but couldn't find a solution to this problem. Interestingly, although there was an error reported, the PMML file was still generated, which confuses me. I tried to import this PMML file using other Python packages, but they all failed. Is there anything wrong with the PMML file I generated? Which Python package do you recommend to import PMML files? I have tried pypmml, sklearn_pmml, and converted it to PKL file first and then to PMML file, but all failed.It's not quite clear whether the PMML file I generated is usable or not Here is my specific code:
```
from sklearn.datasets import make_multilabel_classification
from sklearn.multioutput import MultiOutputClassifier, MultiOutputRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn2pmml import PMMLPipeline
from sklearn2pmml.decoration import ContinuousDomain
from sklearn.preprocessing import StandardScaler
from sklearn2pmml import sklearn2pmml
import pandas as pd

X, y = make_multilabel_classification(n_samples=100, n_features=10, n_classes=3, random_state=1)


classifier = MultiOutputClassifier(DecisionTreeClassifier())

pipeline = PMMLPipeline([
    ("classifier", classifier)
])

pipeline.fit(X, y)

sklearn2pmml(pipeline, "new.pmml", with_repr=True, debug=True)
```
The error message when saving PMML:
```
[d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\pipeline\__init__.py:68](file:///D:/Anaconda3/envs/pycaret3/lib/site-packages/sklearn2pmml/pipeline/__init__.py:68): UserWarning: X is missing feature names. The reproducibility of predictions between Scikit-Learn and PMML can not be guaranteed
  warnings.warn("X is missing feature names. The reproducibility of predictions between Scikit-Learn and PMML can not be guaranteed")
[d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\pipeline\__init__.py:75](file:///D:/Anaconda3/envs/pycaret3/lib/site-packages/sklearn2pmml/pipeline/__init__.py:75): UserWarning: y is missing target field name(s)
  warnings.warn("y is missing target field name(s)")
python: 3.10.10
sklearn: 1.1.1
sklearn2pmml: 0.92.0
joblib: 1.2.0
sklearn_pandas: 2.2.0
pandas: 1.5.3
numpy: 1.24.2
openjdk: 17.0.3
Executing command:
java -cp d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\sklearn2pmml-1.0-SNAPSHOT.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\gson-2.10.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\guava-21.0.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\h2o-genmodel-3.40.0.2.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\h2o-logger-3.40.0.2.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\h2o-tree-api-0.3.17.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\istack-commons-runtime-4.0.1.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\jackson-annotations-2.13.3.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\jakarta.activation-2.0.1.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\jakarta.xml.bind-api-3.0.1.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\jaxb-core-3.0.2.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\jaxb-runtime-3.0.2.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\jcommander-1.72.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\pickle-1.3.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\pmml-converter-1.5.4.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\pmml-h2o-1.2.5.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\pmml-lightgbm-1.4.4.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\pmml-model-1.6.4.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\pmml-model-metro-1.6.4.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\pmml-python-1.1.14.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\pmml-sklearn-1.7.27.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\pmml-sklearn-extension-1.7.27.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\pmml-sklearn-h2o-1.7.27.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\pmml-sklearn-lightgbm-1.7.27.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\pmml-sklearn-statsmodels-1.7.27.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\pmml-sklearn-xgboost-1.7.27.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\pmml-statsmodels-1.0.2.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\pmml-xgboost-1.7.3.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\serpent-1.40.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\slf4j-api-1.7.36.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\slf4j-jdk14-1.7.36.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\ubjson-0.1.8.jar;d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\resources\ubjson-gson-0.1.8.jar com.sklearn2pmml.Main --pkl-pipeline-input C:\Users\lanze\AppData\Local\Temp\pipeline-ywplqx5o.pkl.z --pmml-output new.pmml
Exception in thread Thread-20 (_readerthread):
Traceback (most recent call last):
  File "[d:\Anaconda3\envs\pycaret3\lib\threading.py](file:///D:/Anaconda3/envs/pycaret3/lib/threading.py)", line 1016, in _bootstrap_inner
    self.run()
  File "[d:\Anaconda3\envs\pycaret3\lib\threading.py](file:///D:/Anaconda3/envs/pycaret3/lib/threading.py)", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "[d:\Anaconda3\envs\pycaret3\lib\subprocess.py](file:///D:/Anaconda3/envs/pycaret3/lib/subprocess.py)", line 1499, in _readerthread
    buffer.append(fh.read())
  File "[d:\Anaconda3\envs\pycaret3\lib\codecs.py](file:///D:/Anaconda3/envs/pycaret3/lib/codecs.py)", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 1: invalid continuation byte
Standard output is empty
Preserved joblib dump file(s): [C:\Users\lanze\AppData\Local\Temp\pipeline-ywplqx5o.pkl.z](file:///C:/Users/lanze/AppData/Local/Temp/pipeline-ywplqx5o.pkl.z)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[12], line 21
     15 pipeline = PMMLPipeline([
     16     ("classifier", classifier)
     17 ])
     19 pipeline.fit(X, y)
---> 21 sklearn2pmml(pipeline, "new.pmml", with_repr=True, debug=True)

File [d:\Anaconda3\envs\pycaret3\lib\site-packages\sklearn2pmml\__init__.py:281](file:///D:/Anaconda3/envs/pycaret3/lib/site-packages/sklearn2pmml/__init__.py:281), in sklearn2pmml(pipeline, pmml, with_repr, java_home, java_opts, user_classpath, debug)
    279 else:
    280 	print("Standard output is empty")
--> 281 if len(error) > 0:
    282 	print("Standard error:\n{0}".format(error))
    283 else:

TypeError: object of type 'NoneType' has no len()
```
The error message when importing PMML:
```
Py4JJavaError                             Traceback (most recent call last)
File [d:\Anaconda3\envs\pycaret3\lib\site-packages\pypmml\model.py:192](file:///D:/Anaconda3/envs/pycaret3/lib/site-packages/pypmml/model.py:192), in Model.fromFile(cls, name)
    191 try:
--> 192     java_model = pc._jvm.org.pmml4s.model.Model.fromFile(name)
    193     return cls(java_model)

File [d:\Anaconda3\envs\pycaret3\lib\site-packages\py4j\java_gateway.py:1322](file:///D:/Anaconda3/envs/pycaret3/lib/site-packages/py4j/java_gateway.py:1322), in JavaMember.__call__(self, *args)
   1321 answer = self.gateway_client.send_command(command)
-> 1322 return_value = get_return_value(
   1323     answer, self.gateway_client, self.target_id, self.name)
   1325 for temp_arg in temp_args:

File [d:\Anaconda3\envs\pycaret3\lib\site-packages\py4j\protocol.py:326](file:///D:/Anaconda3/envs/pycaret3/lib/site-packages/py4j/protocol.py:326), in get_return_value(answer, gateway_client, target_id, name)
    325 if answer[1] == REFERENCE_TYPE:
--> 326     raise Py4JJavaError(
    327         "An error occurred while calling {0}{1}{2}.\n".
    328         format(target_id, ".", name), value)
    329 else:

Py4JJavaError: An error occurred while calling z:org.pmml4s.model.Model.fromFile.
: java.util.NoSuchElementException: No value found for 'x-multiModelChain'
	at scala.Enumeration.withName(Enumeration.scala:124)
	at org.pmml4s.xml.MiningBuilder$$anon$1.build(MiningBuilder.scala:92)
	at org.pmml4s.xml.MiningBuilder$$anon$1.build(MiningBuilder.scala:90)
...
    194 except Py4JJavaError as e:
    195     je = e.java_exception
--> 196     raise PmmlError(je.getClass().getSimpleName(), je.getMessage())

PmmlError: ('NoSuchElementException', "No value found for 'x-multiModelChain'")
```

**Comment by vruusmann** [comment] 2023-04-24 06:36
> I tried updating sklearn2pmml to version 0.92.0 and the previous issue disappeared

This issue actually looks like a duplicate of https://github.com/jpmml/jpmml-python/issues/19

> Interestingly, although there was an error reported, the PMML file was still generated.

I don't see any errors in your sample output.

There are two warnings about missing column names ("X is missing feature names" and "y is missing target field name(s)").

PMML identifies fields by name (not by column index). So, if your training datasets do not provide meaningful column names, then it will be very difficult to use these PMML documents for prediction (because you can't make any assumptions about the ordering of column in the testing datasets).

It actually makes me think that SkLearn2PMML should promote these two warnings to errors - the converter should refuse to deal with pipelines that have been trained on anonymous columns.

> Is there anything wrong with the PMML file I generated?

You're training a multi-output model (ie. the `y` dataset has more than one column).

The representation of multi-output models is not covered in PMML schema version 4.4. The JPMML faily of libraries uses an `x-multiModelChain` vendor extension to implement it.

See https://github.com/jpmml/sklearn2pmml/issues/374

> Which Python package do you recommend to import PMML files?

Use [JPMML-Evaluator-Python](https://github.com/jpmml/jpmml-evaluator-python)

**Closed by vruusmann** 2023-04-24 06:36 UTC
